In [137]:
import pickle
import pandas as pd

In [138]:
!ls

2.5kmX2.5km_nhd_variables_extracted_stripped
200mX200m_nhd_variables_extracted_stripped
2021.03.09_ssurgo_nhd_merged
2021.03.17_Merge_all_datasets.ipynb
2021.03.17_full_dataset
2021.03.17_full_dataset.csv
2021.03.17_us_county_raw
2021.03.19_ssurgo_variables_full
combined_regular_clean_with_ssurgo_variables.csv
df_srtm_slope_variables_200m
df_srtm_slope_variables_2500m
nwi_extracted_features_200X200m
nwi_extracted_features_2500X2500m

In [139]:
# Baseline
df_baseline = pd.read_csv("combined_regular_clean_with_ssurgo_variables.csv")

# NHD
df_nhd_200m = pd.read_pickle("200mX200m_nhd_variables_extracted_stripped")
df_nhd_2500m = pd.read_pickle("2.5kmX2.5km_nhd_variables_extracted_stripped")

# SSURGO
df_ssurgo = pd.read_pickle("2021.03.19_ssurgo_variables_full")

# NWI
df_nwi_200m = pd.read_pickle("nwi_extracted_features_200X200m")
df_nwi_2500m = pd.read_pickle("nwi_extracted_features_2500X2500m")

# srtm, slope, jrc
df_srtm_200m = pd.read_pickle("df_srtm_slope_variables_200m")
df_srtm_2500m = pd.read_pickle("df_srtm_slope_variables_2500m")

# county
df_county = pd.read_pickle("2021.03.17_us_county_raw")

In [140]:
# Baseline
full_columns = list(df_baseline.columns)
delete_columns = ['Unnamed: 0', 'Unnamed: 0.1','index','mukey',
       'hydclprs', 'aws025wta', 'drclassdcd',  'project_name']

imp_columns = list(set(full_columns) - set(delete_columns))
df_baseline = df_baseline[imp_columns]
df_baseline.columns

Index(['cwa4', 'cwa8', 'cwa7', 'cwa_determination', 'cwa5', 'longitude',
       'cwa3', 'date_issued_or_denied', 'latitude', 'Index', 'cwa1',
       'da_number', 'jurisdiction_type', 'rha_determination', 'cwa9', 'cwa2',
       'rha2', 'potential_wetland', 'district', 'cwa6', 'rha1'],
      dtype='object')

In [141]:
# SSURGO
set(df_ssurgo.columns)

delete_columns = ['Unnamed: 0',
 'Unnamed: 0.1',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'cwa_determination',
 'da_number',
 'date_issued_or_denied',
 'district','fl_areasqkm_count_200m',
 'fl_areasqkm_count_2500m',
 'fl_areasqkm_mean_200m',
 'fl_areasqkm_mean_2500m',
 'fl_areasqkm_sum_200m',
 'fl_areasqkm_sum_2500m',
 'fl_comid_list_200m',
 'fl_comid_list_2500m',
 'fl_comid_str_200m',
 'fl_comid_str_2500m',
 'fl_divergence_count_200m',
 'fl_divergence_count_2500m',
 'fl_divergence_mean_200m',
 'fl_divergence_mean_2500m',
 'fl_divergence_sum_200m',
 'fl_divergence_sum_2500m',
 'fl_flow_type_count_200m',
 'fl_flow_type_count_2500m',
 'fl_flow_type_mean_200m',
 'fl_flow_type_mean_2500m',
 'fl_flow_type_sum_200m',
 'fl_flow_type_sum_2500m',
 'fl_ftype_str_200m',
 'fl_ftype_str_2500m',
 'fl_ftype_str_list_200m',
 'fl_ftype_str_list_2500m',
 'fl_gnis_id_list_200m',
 'fl_gnis_id_list_2500m',
 'fl_gnis_id_str_200m',
 'fl_gnis_id_str_2500m',
 'fl_gnis_name_ind_count_200m',
 'fl_gnis_name_ind_count_2500m',
 'fl_gnis_name_ind_mean_200m',
 'fl_gnis_name_ind_mean_2500m',
 'fl_gnis_name_ind_sum_200m',
 'fl_gnis_name_ind_sum_2500m',
 'fl_intephem_count_200m',
 'fl_intephem_count_2500m',
 'fl_intephem_mean_200m',
 'fl_intephem_mean_2500m',
 'fl_intephem_sum_200m',
 'fl_intephem_sum_2500m',
 'fl_length_count_200m',
 'fl_length_count_2500m',
 'fl_length_list_200m',
 'fl_length_list_2500m',
 'fl_length_mean_200m',
 'fl_length_mean_2500m',
 'fl_length_sum_200m',
 'fl_length_sum_2500m',
 'fl_startflag_count_200m',
 'fl_startflag_count_2500m',
 'fl_startflag_mean_200m',
 'fl_startflag_mean_2500m',
 'fl_startflag_sum_200m',
 'fl_startflag_sum_2500m',
 'fl_streamorde_count_200m',
 'fl_streamorde_count_2500m',
 'fl_streamorde_mean_200m',
 'fl_streamorde_mean_2500m',
 'fl_streamorde_sum_200m',
 'fl_streamorde_sum_2500m',
 'fl_totdasqkm_count_200m',
 'fl_totdasqkm_count_2500m',
 'fl_totdasqkm_mean_200m',
 'fl_totdasqkm_mean_2500m',
 'fl_totdasqkm_sum_200m',
 'fl_totdasqkm_sum_2500m','index',
 'jurisdiction_type',
 'latitude',
 'longitude','nhd_vars_fl_200m',
 'nhd_vars_fl_2500m',
 'nhd_vars_wb_200m',
 'nhd_vars_wb_2500m','potential_wetland',
 'project_name',
 'rha1',
 'rha2',
 'rha_determination','wb_area_count_200m',
 'wb_area_count_2500m',
 'wb_area_list_200m',
 'wb_area_list_2500m',
 'wb_area_mean_200m',
 'wb_area_mean_2500m',
 'wb_area_sum_200m',
 'wb_area_sum_2500m',
 'wb_comid_list_200m',
 'wb_comid_list_2500m',
 'wb_comid_str_200m',
 'wb_comid_str_2500m',
 'wb_ftype_str_200m',
 'wb_ftype_str_2500m',
 'wb_ftype_str_list_200m',
 'wb_ftype_str_list_2500m',
 'wb_gnis_id_list_200m',
 'wb_gnis_id_list_2500m',
 'wb_gnis_id_str_200m',
 'wb_gnis_id_str_2500m',
 'wb_gnis_name_ind_count_200m',
 'wb_gnis_name_ind_count_2500m',
 'wb_gnis_name_ind_mean_200m',
 'wb_gnis_name_ind_mean_2500m',
 'wb_gnis_name_ind_sum_200m',
 'wb_gnis_name_ind_sum_2500m']

full_columns = list(df_ssurgo.columns)
imp_columns = list(set(full_columns) - set(delete_columns))
df_ssurgo = df_ssurgo[imp_columns]
df_ssurgo

,drclasswet,mustatus,engstafll,mukey,engcmssmp,engdwbml,forpehrtdc,wtdepaprju,hydgrpdcd,iccdcd,...,engsldcp,aws0100wta,slopegradw,slopegradd,drclassdcd,aws025wta,engsldcd,urbrecptwt,niccdcdpct,wtdepannmi
0,Very poorly drained,NaN,Not rated,289404.0,Not rated,Very limited,Slight,0.0,A/D,NaN,...,Very limited,28.21,1.0,1.0,Very poorly drained,7.40,Very limited,1.000,80.0,0.0
1,NaN,NaN,Not rated,293511.0,Not rated,Not rated,Not rated,0.0,NaN,NaN,...,Not rated,0.00,0.0,0.0,NaN,0.00,Not rated,0.000,100.0,0.0
2,NaN,NaN,Not rated,295436.0,Not rated,Not rated,Not rated,0.0,NaN,NaN,...,Not rated,0.00,0.0,0.0,NaN,0.00,Not rated,0.000,100.0,0.0
3,Moderately well drained,NaN,Not rated,290780.0,Not rated,Very limited,Slight,54.0,C/D,NaN,...,Very limited,7.74,2.0,2.0,Moderately well drained,2.25,Very limited,0.604,75.0,54.0
4,Poorly drained,NaN,Very limited,293019.0,Poor,Very limited,Slight,0.0,C/D,NaN,...,Very limited,16.53,1.0,1.0,Poorly drained,5.20,Very limited,0.999,89.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14614,Somewhat poorly drained,NaN,Not rated,564873.0,Not rated,Very limited,Slight,31.0,D,NaN,...,Very limited,16.83,2.0,2.0,Somewhat poorly drained,5.50,Very limited,0.998,90.0,31.0
14615,Well drained,NaN,Somewhat limited,566474.0,Poor,Not limited,Moderate,0.0,B,NaN,...,Somewhat limited,16.60,5.0,5.0,Well drained,3.85,Somewhat limited,0.046,100.0,0.0
14616,Somewhat excessively drained,NaN,Very limited,106656.0,Fair,Very limited,Severe,0.0,D,NaN,...,Very limited,6.13,14.0,15.0,Somewhat excessively drained,3.61,Very limited,0.037,90.0,0.0
14617,Well drained,NaN,Not rated,384352.0,Not rated,Very limited,Moderate,0.0,D,NaN,...,Somewhat limited,16.88,4.0,4.0,Well drained,4.45,Somewhat limited,0.254,89.0,0.0
14618,Well drained,NaN,Not rated,383437.0,Not rated,Not rated,Slight,0.0,B,NaN,...,Somewhat limited,14.45,2.0,2.0,Well drained,3.75,Somewhat limited,0.446,90.0,0.0

In [142]:
# NHD
full_columns_200m = list(df_nhd_200m.columns)
full_columns_2500m = list(df_nhd_2500m.columns)
full_columns
delete_columns_200m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb_200m',
       'nhd_vars_fl_200m', 'wb_comid_list_200m', 'wb_ftype_str_list_200m',
       'wb_gnis_id_list_200m', 'wb_area_list_200m', 'fl_comid_list_200m',
       'fl_ftype_str_list_200m', 'fl_gnis_id_list_200m', 'fl_length_list_200m',
                 'wb_comid_str_200m', 'wb_ftype_str_200m', 'wb_gnis_id_str_200m',
                 'fl_comid_str_200m', 'fl_ftype_str_200m',
       'fl_gnis_id_str_200m','fl_ftype_str_vector_200m',
       'wb_ftype_str_vector_200m']

delete_columns_2500m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb_2500m',
       'nhd_vars_fl_2500m', 'wb_comid_list_2500m', 'wb_ftype_str_list_2500m',
       'wb_gnis_id_list_2500m', 'wb_area_list_2500m', 'fl_comid_list_2500m',
       'fl_ftype_str_list_2500m', 'fl_gnis_id_list_2500m', 'fl_length_list_2500m',
                 'wb_comid_str_2500m', 'wb_ftype_str_2500m', 'wb_gnis_id_str_2500m',
                 'fl_comid_str_2500m', 'fl_ftype_str_2500m',
       'fl_gnis_id_str_2500m','fl_ftype_str_vector_2500m',
       'wb_ftype_str_vector_2500m']

imp_columns_200m = list(set(full_columns_200m) - set(delete_columns_200m))
imp_columns_2500m = list(set(full_columns_2500m) - set(delete_columns_2500m))

df_nhd_200m = df_nhd_200m[imp_columns_200m]
df_nhd_2500m = df_nhd_2500m[imp_columns_2500m]

In [143]:
# NWI
full_columns_200m = list(df_nwi_200m.columns)
full_columns_2500m = list(df_nwi_2500m.columns)


delete_columns_200m = ['CLASS_NAME_vector_200m',
 'FIRST_MODIFIER_NAME_vector_200m',
 'SPLIT_CLASS_NAME_vector_200m',
 'SPLIT_SUBCLASS_NAME_vector_200m',
 'SUBCLASS_NAME_vector_200m',
 'SUBSYSTEM_NAME_vector_200m',
 'SYSTEM_NAME_vector_200m',
 'Unnamed: 0',
 'Unnamed: 0.1',
 'WATER_REGIME_NAME_vector_200m',
 'WATER_REGIME_SUBGROUP_vector_200m',
 'aws025wta',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'cwa_determination',
 'da_number',
 'date_issued_or_denied',
 'district',
 'drclassdcd',
 'hydclprs',
 'index',
 'jurisdiction_type',
 'latitude',
 'longitude',
 'mukey','nwi_attr_list_200m',
 'nwi_bbox_vars_200m','potential_wetland',
 'project_name',
 'rha1',
 'rha2',
 'rha_determination',
 'wetland_type_vector_200m']

delete_columns_2500m = ['CLASS_NAME_vector_2500m',
 'FIRST_MODIFIER_NAME_vector_2500m',
 'SPLIT_CLASS_NAME_vector_2500m',
 'SPLIT_SUBCLASS_NAME_vector_2500m',
 'SUBCLASS_NAME_vector_2500m',
 'SUBSYSTEM_NAME_vector_2500m',
 'SYSTEM_NAME_vector_2500m',
 'Unnamed: 0',
 'Unnamed: 0.1',
 'WATER_REGIME_NAME_vector_2500m',
 'WATER_REGIME_SUBGROUP_vector_2500m',
 'aws025wta',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'cwa_determination',
 'da_number',
 'date_issued_or_denied',
 'district',
 'drclassdcd',
 'hydclprs',
 'index',
 'jurisdiction_type',
 'latitude',
 'longitude',
 'mukey','nwi_attr_list_2500m',
 'nwi_bbox_vars_2500m','nwi_feature_count_2500m','potential_wetland',
 'project_name',
 'rha1',
 'rha2',
 'rha_determination',
 'wetland_type_vector_2500m']

imp_columns_200m = list(set(full_columns_200m) - set(delete_columns_200m))
imp_columns_2500m = list(set(full_columns_2500m) - set(delete_columns_2500m))

df_nwi_200m = df_nwi_200m[imp_columns_200m]
df_nwi_2500m = df_nwi_2500m[imp_columns_2500m]

In [144]:
# SRTM, JRC

full_columns_200m = list(df_srtm_200m.columns)
full_columns_2500m = list(df_srtm_2500m.columns)


delete_columns_200m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'elevation_stats_200m',
       'slope_stats_200m', 'seasonality_stats_200m', 'recurrence_stats_200m',
       'transition_hist', ]
df_srtm_2500m.columns
delete_columns_2500m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'elevation_stats_2500m',
       'slope_stats_2500m', 'seasonality_stats_2500m',
       'recurrence_stats_2500m', 'transition_hist', ]

imp_columns_200m = list(set(full_columns_200m) - set(delete_columns_200m))
imp_columns_2500m = list(set(full_columns_2500m) - set(delete_columns_2500m))

df_srtm_200m = df_srtm_200m[imp_columns_200m]
df_srtm_2500m = df_srtm_2500m[imp_columns_2500m]

In [145]:
# County, State

full_columns = list(df_county.columns)

delete_columns = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd',]


imp_columns = list(set(full_columns) - set(delete_columns))

df_county = df_county[imp_columns]
df_county.columns

Index(['Index', 'county', 'state'], dtype='object')

In [146]:
# full_columns_200m = list(df_nwi_200m.columns)
# full_columns_2500m = list(df_nwi_2500m.columns)


# delete_columns_200m = []
# delete_columns_2500m = []

# imp_columns_200m = list(set(full_columns_200m) - set(delete_columns_200m))
# imp_columns_2500m = list(set(full_columns_2500m) - set(delete_columns_2500m))

# df_nwi_200m = df_nwi_200m[imp_columns_200m]
# df_nwi_2500m = df_nwi_2500m[imp_columns_2500m]

In [147]:
# col_nhd_200m_delta = ["Index"] + list(set(df_nhd_200m.columns) - set(df_baseline.columns)) 
# col_nhd_2500m_delta = ["Index"] + list(set(df_nhd_2500m.columns) - set(df_baseline.columns)) 

# col_ssurgo_delta = ["Index"] + list(set(df_ssurgo.columns) - set(df_baseline.columns)) 

# col_nwi_200m_delta = ["Index"] + list(set(df_nwi_200m.columns) - set(df_baseline.columns)) 
# col_nwi_2500m_delta = ["Index"] + list(set(df_nwi_2500m.columns) - set(df_baseline.columns)) 

# col_srtm_200m_delta = ["Index"] + list(set(df_srtm_200m.columns) - set(df_baseline.columns)) 
# col_srtm_2500m_delta = ["Index"] + list(set(df_srtm_2500m.columns) - set(df_baseline.columns)) 

# col_county_delta = ["Index"] + list(set(df_county.columns) - set(df_baseline.columns))

In [148]:
# df_nhd_200m_delta = df_nhd_200m[col_nhd_200m_delta]
# df_nhd_2500m_delta = df_nhd_2500m[col_nhd_2500m_delta]

# df_ssurgo_delta = df_ssurgo[col_ssurgo_delta]

# df_nwi_200m_delta = df_nwi_200m[col_nwi_200m_delta]
# df_nwi_2500m_delta = df_nwi_2500m[col_nwi_2500m_delta]

# df_srtm_200m_delta = df_srtm_200m[col_srtm_200m_delta]
# df_srtm_2500m_delta = df_srtm_2500m[col_srtm_2500m_delta]

# df_county_delta = df_county[col_county_delta]

In [149]:
df1 = df_baseline
df2 = df_ssurgo

df3 = df_srtm_200m
df4 = df_nhd_200m
df5 = df_nwi_200m

df6 = df_srtm_2500m
df7 = df_nhd_2500m
df8 = df_nwi_2500m

df9 = df_county

df_merged = pd.merge(df1, df2, on="Index")
df_merged = pd.merge(df_merged, df3, on="Index")
df_merged = pd.merge(df_merged, df4, on="Index")
df_merged = pd.merge(df_merged, df5, on="Index")
df_merged = pd.merge(df_merged, df6, on="Index")
df_merged = pd.merge(df_merged, df7, on="Index")
df_merged = pd.merge(df_merged, df8, on="Index")
df_merged = pd.merge(df_merged, df9, on="Index")
set(df_merged.columns)

{'Index',
 'awmmfpwwta',
 'aws0100wta',
 'aws0150wta',
 'aws025wta',
 'aws050wta',
 'brockdepmi',
 'county',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'cwa_determination',
 'da_number',
 'date_issued_or_denied',
 'district',
 'drclassdcd',
 'drclasswet',
 'elevation_max_200m',
 'elevation_max_2500m',
 'elevation_mean_200m',
 'elevation_mean_2500m',
 'elevation_min_200m',
 'elevation_min_2500m',
 'elevation_stdev_200m',
 'elevation_stdev_2500m',
 'engcmssdcd',
 'engcmssmp',
 'engdwbdcd',
 'engdwbll',
 'engdwbml',
 'engdwobdcd',
 'englrsdcd',
 'engsldcd',
 'engsldcp',
 'engstafdcd',
 'engstafll',
 'engstafml',
 'fl_areasqkm_count_200m',
 'fl_areasqkm_count_2500m',
 'fl_areasqkm_mean_200m',
 'fl_areasqkm_mean_2500m',
 'fl_areasqkm_sum_200m',
 'fl_areasqkm_sum_2500m',
 'fl_divergence_count_200m',
 'fl_divergence_count_2500m',
 'fl_divergence_mean_200m',
 'fl_divergence_mean_2500m',
 'fl_divergence_sum_200m',
 'fl_divergence_sum_2500m',
 'fl_flow_type_count_200m',
 'fl_flow_type_count_2500m',
 'fl_flow_type_mean_200m',
 'fl_flow_type_mean_2500m',
 'fl_flow_type_sum_200m',
 'fl_flow_type_sum_2500m',
 'fl_ftype_artificialpath_200m',
 'fl_ftype_artificialpath_2500m',
 'fl_ftype_canalditch_200m',
 'fl_ftype_canalditch_2500m',
 'fl_ftype_coastline_200m',
 'fl_ftype_coastline_2500m',
 'fl_ftype_connector_200m',
 'fl_ftype_connector_2500m',
 'fl_ftype_pipeline_200m',
 'fl_ftype_pipeline_2500m',
 'fl_ftype_streamriver_200m',
 'fl_ftype_streamriver_2500m',
 'fl_gnis_name_ind_count_200m',
 'fl_gnis_name_ind_count_2500m',
 'fl_gnis_name_ind_mean_200m',
 'fl_gnis_name_ind_mean_2500m',
 'fl_gnis_name_ind_sum_200m',
 'fl_gnis_name_ind_sum_2500m',
 'fl_intephem_count_200m',
 'fl_intephem_count_2500m',
 'fl_intephem_mean_200m',
 'fl_intephem_mean_2500m',
 'fl_intephem_sum_200m',
 'fl_intephem_sum_2500m',
 'fl_length_count_200m',
 'fl_length_count_2500m',
 'fl_length_mean_200m',
 'fl_length_mean_2500m',
 'fl_length_sum_200m',
 'fl_length_sum_2500m',
 'fl_startflag_count_200m',
 'fl_startflag_count_2500m',
 'fl_startflag_mean_200m',
 'fl_startflag_mean_2500m',
 'fl_startflag_sum_200m',
 'fl_startflag_sum_2500m',
 'fl_streamorde_count_200m',
 'fl_streamorde_count_2500m',
 'fl_streamorde_mean_200m',
 'fl_streamorde_mean_2500m',
 'fl_streamorde_sum_200m',
 'fl_streamorde_sum_2500m',
 'fl_totdasqkm_count_200m',
 'fl_totdasqkm_count_2500m',
 'fl_totdasqkm_mean_200m',
 'fl_totdasqkm_mean_2500m',
 'fl_totdasqkm_sum_200m',
 'fl_totdasqkm_sum_2500m',
 'flodfreqdc',
 'flodfreqma',
 'forpehrtdc',
 'hydclprs',
 'hydgrpdcd',
 'iccdcd',
 'iccdcdpct',
 'jurisdiction_type',
 'latitude',
 'longitude',
 'mukey',
 'mustatus',
 'niccdcd',
 'niccdcdpct',
 'nwi_CLASS_NAME_aquatic_bed_200m',
 'nwi_CLASS_NAME_aquatic_bed_2500m',
 'nwi_CLASS_NAME_emergent_200m',
 'nwi_CLASS_NAME_emergent_2500m',
 'nwi_CLASS_NAME_forested_200m',
 'nwi_CLASS_NAME_forested_2500m',
 'nwi_CLASS_NAME_moss-lichen_200m',
 'nwi_CLASS_NAME_moss-lichen_2500m',
 'nwi_CLASS_NAME_reef_200m',
 'nwi_CLASS_NAME_reef_2500m',
 'nwi_CLASS_NAME_rock_bottom_200m',
 'nwi_CLASS_NAME_rock_bottom_2500m',
 'nwi_CLASS_NAME_rocky_shore_200m',
 'nwi_CLASS_NAME_rocky_shore_2500m',
 'nwi_CLASS_NAME_scrub-shrub_200m',
 'nwi_CLASS_NAME_scrub-shrub_2500m',
 'nwi_CLASS_NAME_streambed_200m',
 'nwi_CLASS_NAME_streambed_2500m',
 'nwi_CLASS_NAME_unconsolidated_bottom_200m',
 'nwi_CLASS_NAME_unconsolidated_bottom_2500m',
 'nwi_CLASS_NAME_unconsolidated_shore_200m',
 'nwi_CLASS_NAME_unconsolidated_shore_2500m',
 'nwi_CLASS_NAME_zzz_200m',
 'nwi_CLASS_NAME_zzz_2500m',
 'nwi_FIRST_MODIFIER_NAME_acid_200m',
 'nwi_FIRST_MODIFIER_NAME_acid_2500m',
 'nwi_FIRST_MODIFIER_NAME_alkaline_200m',
 'nwi_FIRST_MODIFIER_NAME_alkaline_2500m',
 'nwi_FIRST_MODIFIER_NAME_artificial_substrate_200m',
 'nwi_FIRST_MODIFIER_NAME_artificial_substrate_2500m',
 'nwi_FIRST_MODIFIER_NAME_beaver_200m',
 'nwi_FIRST_MODIFIER_NAME_beaver_2500m',
 'nwi_FIRST_MODIFIER_NAME_diked/impounded_200m',
 'nwi_FIRST_MODIFIER_NAME_diked/impounded_2500m',
 'nwi_FIRST_MODIFIER_NAME_euthaline/eusaline_200m',
 'nwi_FIRST_MODIFIER_NAME_euthaline/eusaline_2500m',
 'nwi_FIRST_MODIFIER_NAME_excavated_200m',
 'nwi_FIRST_MODIFIER_NAME_excavated_2500m',
 'nwi_FIRST_MODIFIER_NAME_farmed_200m',
 'nwi_FIRST_MODIFIER_NAME_farmed_2500m',
 'nwi_FIRST_MODIFIER_NAME_hyperhaline/hypersaline_200m',
 'nwi_FIRST_MODIFIER_NAME_hyperhaline/hypersaline_2500m',
 'nwi_FIRST_MODIFIER_NAME_managed_200m',
 'nwi_FIRST_MODIFIER_NAME_managed_2500m',
 'nwi_FIRST_MODIFIER_NAME_mesohaline_200m',
 'nwi_FIRST_MODIFIER_NAME_mesohaline_2500m',
 'nwi_FIRST_MODIFIER_NAME_mineral_200m',
 'nwi_FIRST_MODIFIER_NAME_mineral_2500m',
 'nwi_FIRST_MODIFIER_NAME_mixohaline/mixosaline_(brackish)_200m',
 'nwi_FIRST_MODIFIER_NAME_mixohaline/mixosaline_(brackish)_2500m',
 'nwi_FIRST_MODIFIER_NAME_oligohaline_200m',
 'nwi_FIRST_MODIFIER_NAME_oligohaline_2500m',
 'nwi_FIRST_MODIFIER_NAME_organic_200m',
 'nwi_FIRST_MODIFIER_NAME_organic_2500m',
 'nwi_FIRST_MODIFIER_NAME_partially_drained/ditched_200m',
 'nwi_FIRST_MODIFIER_NAME_partially_drained/ditched_2500m',
 'nwi_FIRST_MODIFIER_NAME_polyhaline_200m',
 'nwi_FIRST_MODIFIER_NAME_polyhaline_2500m',
 'nwi_FIRST_MODIFIER_NAME_spoil_200m',
 'nwi_FIRST_MODIFIER_NAME_spoil_2500m',
 'nwi_FIRST_MODIFIER_NAME_zzz_200m',
 'nwi_FIRST_MODIFIER_NAME_zzz_2500m',
 'nwi_SPLIT_CLASS_NAME_aquatic_bed_200m',
 'nwi_SPLIT_CLASS_NAME_aquatic_bed_2500m',
 'nwi_SPLIT_CLASS_NAME_emergent_200m',
 'nwi_SPLIT_CLASS_NAME_emergent_2500m',
 'nwi_SPLIT_CLASS_NAME_forested_200m',
 'nwi_SPLIT_CLASS_NAME_forested_2500m',
 'nwi_SPLIT_CLASS_NAME_moss-lichen_200m',
 'nwi_SPLIT_CLASS_NAME_moss-lichen_2500m',
 'nwi_SPLIT_CLASS_NAME_reef_200m',
 'nwi_SPLIT_CLASS_NAME_reef_2500m',
 'nwi_SPLIT_CLASS_NAME_rocky_shore_200m',
 'nwi_SPLIT_CLASS_NAME_rocky_shore_2500m',
 'nwi_SPLIT_CLASS_NAME_scrub-shrub_200m',
 'nwi_SPLIT_CLASS_NAME_scrub-shrub_2500m',
 'nwi_SPLIT_CLASS_NAME_unconsolidated_bottom_200m',
 'nwi_SPLIT_CLASS_NAME_unconsolidated_bottom_2500m',
 'nwi_SPLIT_CLASS_NAME_unconsolidated_shore_200m',
 'nwi_SPLIT_CLASS_NAME_unconsolidated_shore_2500m',
 'nwi_SPLIT_CLASS_NAME_zzz_200m',
 'nwi_SPLIT_CLASS_NAME_zzz_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_algal_200m',
 'nwi_SPLIT_SUBCLASS_NAME_algal_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_aquatic_moss_200m',
 'nwi_SPLIT_SUBCLASS_NAME_aquatic_moss_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_bedrock_200m',
 'nwi_SPLIT_SUBCLASS_NAME_bedrock_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_broad-leaved_deciduous_200m',
 'nwi_SPLIT_SUBCLASS_NAME_broad-leaved_deciduous_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_broad-leaved_evergreen_200m',
 'nwi_SPLIT_SUBCLASS_NAME_broad-leaved_evergreen_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_cobble-gravel_200m',
 'nwi_SPLIT_SUBCLASS_NAME_cobble-gravel_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_coral_200m',
 'nwi_SPLIT_SUBCLASS_NAME_coral_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_dead_200m',
 'nwi_SPLIT_SUBCLASS_NAME_dead_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_deciduous_200m',
 'nwi_SPLIT_SUBCLASS_NAME_deciduous_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_evergreen_200m',
 'nwi_SPLIT_SUBCLASS_NAME_evergreen_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_floating_vascular_200m',
 'nwi_SPLIT_SUBCLASS_NAME_floating_vascular_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_lichen_200m',
 'nwi_SPLIT_SUBCLASS_NAME_lichen_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_mollusk_200m',
 'nwi_SPLIT_SUBCLASS_NAME_mollusk_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_moss_200m',
 'nwi_SPLIT_SUBCLASS_NAME_moss_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_mud_200m',
 'nwi_SPLIT_SUBCLASS_NAME_mud_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_needle-leaved_deciduous_200m',
 'nwi_SPLIT_SUBCLASS_NAME_needle-leaved_deciduous_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_needle-leaved_evergreen_200m',
 'nwi_SPLIT_SUBCLASS_NAME_needle-leaved_evergreen_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_non_persistent_200m',
 'nwi_SPLIT_SUBCLASS_NAME_non_persistent_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_organic_200m',
 'nwi_SPLIT_SUBCLASS_NAME_organic_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_persistent_200m',
 'nwi_SPLIT_SUBCLASS_NAME_persistent_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_phragmites_australis_200m',
 'nwi_SPLIT_SUBCLASS_NAME_phragmites_australis_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_rooted_vascular_200m',
 'nwi_SPLIT_SUBCLASS_NAME_rooted_vascular_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_rubble_200m',
 'nwi_SPLIT_SUBCLASS_NAME_rubble_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_sand_200m',
 'nwi_SPLIT_SUBCLASS_NAME_sand_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_vegetated_200m',
 'nwi_SPLIT_SUBCLASS_NAME_vegetated_2500m',
 'nwi_SPLIT_SUBCLASS_NAME_zzz_200m',
 'nwi_SPLIT_SUBCLASS_NAME_zzz_2500m',
 'nwi_SUBCLASS_NAME_algal_200m',
 'nwi_SUBCLASS_NAME_algal_2500m',
 'nwi_SUBCLASS_NAME_aquatic_moss_200m',
 'nwi_SUBCLASS_NAME_aquatic_moss_2500m',
 'nwi_SUBCLASS_NAME_bedrock_200m',
 'nwi_SUBCLASS_NAME_bedrock_2500m',
 'nwi_SUBCLASS_NAME_broad-leaved_deciduous_200m',
 'nwi_SUBCLASS_NAME_broad-leaved_deciduous_2500m',
 'nwi_SUBCLASS_NAME_broad-leaved_evergreen_200m',
 'nwi_SUBCLASS_NAME_broad-leaved_evergreen_2500m',
 'nwi_SUBCLASS_NAME_cobble-gravel_200m',
 'nwi_SUBCLASS_NAME_cobble-gravel_2500m',
 'nwi_SUBCLASS_NAME_coral_200m',
 'nwi_SUBCLASS_NAME_coral_2500m',
 'nwi_SUBCLASS_NAME_dead_200m',
 'nwi_SUBCLASS_NAME_dead_2500m',
 'nwi_SUBCLASS_NAME_deciduous_200m',
 'nwi_SUBCLASS_NAME_deciduous_2500m',
 'nwi_SUBCLASS_NAME_evergreen_200m',
 'nwi_SUBCLASS_NAME_evergreen_2500m',
 'nwi_SUBCLASS_NAME_floating_vascular_200m',
 'nwi_SUBCLASS_NAME_floating_vascular_2500m',
 'nwi_SUBCLASS_NAME_lichen_200m',
 'nwi_SUBCLASS_NAME_lichen_2500m',
 'nwi_SUBCLASS_NAME_mollusk_200m',
 'nwi_SUBCLASS_NAME_mollusk_2500m',
 'nwi_SUBCLASS_NAME_moss_200m',
 'nwi_SUBCLASS_NAME_moss_2500m',
 'nwi_SUBCLASS_NAME_mud_200m',
 'nwi_SUBCLASS_NAME_mud_2500m',
 'nwi_SUBCLASS_NAME_needle-leaved_deciduous_200m',
 'nwi_SUBCLASS_NAME_needle-leaved_deciduous_2500m',
 'nwi_SUBCLASS_NAME_needle-leaved_evergreen_200m',
 'nwi_SUBCLASS_NAME_needle-leaved_evergreen_2500m',
 'nwi_SUBCLASS_NAME_non_persistent_200m',
 'nwi_SUBCLASS_NAME_non_persistent_2500m',
 'nwi_SUBCLASS_NAME_organic_200m',
 'nwi_SUBCLASS_NAME_organic_2500m',
 'nwi_SUBCLASS_NAME_persistent_200m',
 'nwi_SUBCLASS_NAME_persistent_2500m',
 'nwi_SUBCLASS_NAME_phragmites_australis_200m',
 'nwi_SUBCLASS_NAME_phragmites_australis_2500m',
 'nwi_SUBCLASS_NAME_rooted_vascular_200m',
 'nwi_SUBCLASS_NAME_rooted_vascular_2500m',
 'nwi_SUBCLASS_NAME_rubble_200m',
 'nwi_SUBCLASS_NAME_rubble_2500m',
 'nwi_SUBCLASS_NAME_sand_200m',
 'nwi_SUBCLASS_NAME_sand_2500m',
 'nwi_SUBCLASS_NAME_vegetated_200m',
 'nwi_SUBCLASS_NAME_vegetated_2500m',
 'nwi_SUBCLASS_NAME_zzz_200m',
 'nwi_SUBCLASS_NAME_zzz_2500m',
 'nwi_SUBSYSTEM_NAME_intermittent_200m',
 'nwi_SUBSYSTEM_NAME_intermittent_2500m',
 'nwi_SUBSYSTEM_NAME_intertidal_200m',
 'nwi_SUBSYSTEM_NAME_intertidal_2500m',
 'nwi_SUBSYSTEM_NAME_limnetic_200m',
 'nwi_SUBSYSTEM_NAME_limnetic_2500m',
 'nwi_SUBSYSTEM_NAME_littoral_200m',
 'nwi_SUBSYSTEM_NAME_littoral_2500m',
 'nwi_SUBSYSTEM_NAME_lower_perennial_200m',
 'nwi_SUBSYSTEM_NAME_lower_perennial_2500m',
 'nwi_SUBSYSTEM_NAME_subtidal_200m',
 'nwi_SUBSYSTEM_NAME_subtidal_2500m',
 'nwi_SUBSYSTEM_NAME_tidal_200m',
 'nwi_SUBSYSTEM_NAME_tidal_2500m',
 'nwi_SUBSYSTEM_NAME_unknown_perennial_200m',
 'nwi_SUBSYSTEM_NAME_unknown_perennial_2500m',
 'nwi_SUBSYSTEM_NAME_upper_perennial_200m',
 'nwi_SUBSYSTEM_NAME_upper_perennial_2500m',
 'nwi_SUBSYSTEM_NAME_zzz_200m',
 'nwi_SUBSYSTEM_NAME_zzz_2500m',
 'nwi_SYSTEM_NAME_estuarine_200m',
 'nwi_SYSTEM_NAME_estuarine_2500m',
 'nwi_SYSTEM_NAME_lacustrine_200m',
 'nwi_SYSTEM_NAME_lacustrine_2500m',
 'nwi_SYSTEM_NAME_marine_200m',
 'nwi_SYSTEM_NAME_marine_2500m',
 'nwi_SYSTEM_NAME_palustrine_200m',
 'nwi_SYSTEM_NAME_palustrine_2500m',
 'nwi_SYSTEM_NAME_riverine_200m',
 'nwi_SYSTEM_NAME_riverine_2500m',
 'nwi_WATER_REGIME_NAME_artificially_flooded_200m',
 'nwi_WATER_REGIME_NAME_artificially_flooded_2500m',
 'nwi_WATER_REGIME_NAME_continuously__saturated_200m',
 'nwi_WATER_REGIME_NAME_continuously__saturated_2500m',
 'nwi_WATER_REGIME_NAME_intermittently_exposed_200m',
 'nwi_WATER_REGIME_NAME_intermittently_exposed_2500m',
 'nwi_WATER_REGIME_NAME_intermittently_flooded_200m',
 'nwi_WATER_REGIME_NAME_intermittently_flooded_2500m',
 'nwi_WATER_REGIME_NAME_irregularly_exposed_200m',
 'nwi_WATER_REGIME_NAME_irregularly_exposed_2500m',
 'nwi_WATER_REGIME_NAME_irregularly_flooded_200m',
 'nwi_WATER_REGIME_NAME_irregularly_flooded_2500m',
 'nwi_WATER_REGIME_NAME_permanently_flooded-tidal_200m',
 'nwi_WATER_REGIME_NAME_permanently_flooded-tidal_2500m',
 'nwi_WATER_REGIME_NAME_permanently_flooded_200m',
 'nwi_WATER_REGIME_NAME_permanently_flooded_2500m',
 'nwi_WATER_REGIME_NAME_regularly_flooded_200m',
 'nwi_WATER_REGIME_NAME_regularly_flooded_2500m',
 'nwi_WATER_REGIME_NAME_seasonally_flooded-tidal_200m',
 'nwi_WATER_REGIME_NAME_seasonally_flooded-tidal_2500m',
 'nwi_WATER_REGIME_NAME_seasonally_flooded/saturated_200m',
 'nwi_WATER_REGIME_NAME_seasonally_flooded/saturated_2500m',
 'nwi_WATER_REGIME_NAME_seasonally_flooded_200m',
 'nwi_WATER_REGIME_NAME_seasonally_flooded_2500m',
 'nwi_WATER_REGIME_NAME_seasonally_saturated_200m',
 'nwi_WATER_REGIME_NAME_seasonally_saturated_2500m',
 'nwi_WATER_REGIME_NAME_semipermanently_flooded-tidal_200m',
 'nwi_WATER_REGIME_NAME_semipermanently_flooded-tidal_2500m',
 'nwi_WATER_REGIME_NAME_semipermanently_flooded_200m',
 'nwi_WATER_REGIME_NAME_semipermanently_flooded_2500m',
 'nwi_WATER_REGIME_NAME_subtidal_200m',
 'nwi_WATER_REGIME_NAME_subtidal_2500m',
 'nwi_WATER_REGIME_NAME_temporary_flooded-tidal_200m',
 'nwi_WATER_REGIME_NAME_temporary_flooded-tidal_2500m',
 'nwi_WATER_REGIME_NAME_temporary_flooded_200m',
 'nwi_WATER_REGIME_NAME_temporary_flooded_2500m',
 'nwi_WATER_REGIME_NAME_zzz_200m',
 'nwi_WATER_REGIME_NAME_zzz_2500m',
 'nwi_WATER_REGIME_SUBGROUP_freshwater_tidal_200m',
 'nwi_WATER_REGIME_SUBGROUP_freshwater_tidal_2500m',
 'nwi_WATER_REGIME_SUBGROUP_nontidal_200m',
 'nwi_WATER_REGIME_SUBGROUP_nontidal_2500m',
 'nwi_WATER_REGIME_SUBGROUP_saltwater_tidal_200m',
 'nwi_WATER_REGIME_SUBGROUP_saltwater_tidal_2500m',
 'nwi_WATER_REGIME_SUBGROUP_zzz_200m',
 'nwi_WATER_REGIME_SUBGROUP_zzz_2500m',
 'nwi_estuarine_and_marine_deepwater_200m',
 'nwi_estuarine_and_marine_deepwater_2500m',
 'nwi_estuarine_and_marine_wetland_200m',
 'nwi_estuarine_and_marine_wetland_2500m',
 'nwi_feature_count_200m',
 'nwi_freshwater_emergent_wetland_200m',
 'nwi_freshwater_emergent_wetland_2500m',
 'nwi_freshwater_forested_200m',
 'nwi_freshwater_forested_2500m',
 'nwi_freshwater_pond_200m',
 'nwi_freshwater_pond_2500m',
 'nwi_lake_200m',
 'nwi_lake_2500m',
 'nwi_other_200m',
 'nwi_other_2500m',
 'nwi_riverine_200m',
 'nwi_riverine_2500m',
 'nwi_shrub_wetland_200m',
 'nwi_shrub_wetland_2500m',
 'nwi_wetland_list_200m',
 'nwi_wetland_list_2500m',
 'pondfreqpr',
 'potential_wetland',
 'recurrence_max_200m',
 'recurrence_max_2500m',
 'recurrence_mean_200m',
 'recurrence_mean_2500m',
 'recurrence_min_200m',
 'recurrence_min_2500m',
 'recurrence_stdev_200m',
 'recurrence_stdev_2500m',
 'rha1',
 'rha2',
 'rha_determination',
 'seasonality_max_200m',
 'seasonality_max_2500m',
 'seasonality_mean_200m',
 'seasonality_mean_2500m',
 'seasonality_min_200m',
 'seasonality_min_2500m',
 'seasonality_stdev_200m',
 'seasonality_stdev_2500m',
 'slope_max_200m',
 'slope_max_2500m',
 'slope_mean_200m',
 'slope_mean_2500m',
 'slope_min_200m',
 'slope_min_2500m',
 'slope_stdev_200m',
 'slope_stdev_2500m',
 'slopegradd',
 'slopegradw',
 'state',
 'transition_0_200m',
 'transition_0_2500m',
 'transition_1_200m',
 'transition_1_2500m',
 'transition_2_200m',
 'transition_2_2500m',
 'transition_3_200m',
 'transition_3_2500m',
 'transition_4_200m',
 'transition_4_2500m',
 'transition_5_200m',
 'transition_5_2500m',
 'transition_6_200m',
 'transition_6_2500m',
 'transition_7_200m',
 'transition_7_2500m',
 'transition_8_200m',
 'transition_8_2500m',
 'transition_9_200m',
 'transition_9_2500m',
 'urbrecptdc',
 'urbrecptwt',
 'wb_area_count_200m',
 'wb_area_count_2500m',
 'wb_area_mean_200m',
 'wb_area_mean_2500m',
 'wb_area_sum_200m',
 'wb_area_sum_2500m',
 'wb_ftype_artificialpath_200m',
 'wb_ftype_artificialpath_2500m',
 'wb_ftype_canalditch_200m',
 'wb_ftype_canalditch_2500m',
 'wb_ftype_coastline_200m',
 'wb_ftype_coastline_2500m',
 'wb_ftype_connector_200m',
 'wb_ftype_connector_2500m',
 'wb_ftype_pipeline_200m',
 'wb_ftype_pipeline_2500m',
 'wb_ftype_streamriver_200m',
 'wb_ftype_streamriver_2500m',
 'wb_gnis_name_ind_count_200m',
 'wb_gnis_name_ind_count_2500m',
 'wb_gnis_name_ind_mean_200m',
 'wb_gnis_name_ind_mean_2500m',
 'wb_gnis_name_ind_sum_200m',
 'wb_gnis_name_ind_sum_2500m',
 'wtdepannmi',
 'wtdepaprju'}

In [150]:
df_merged.columns

Index(['cwa4', 'cwa8', 'cwa7', 'cwa_determination', 'cwa5', 'longitude',
       'cwa3', 'date_issued_or_denied', 'latitude', 'Index',
       ...
       'nwi_SUBCLASS_NAME_non_persistent_2500m',
       'nwi_SPLIT_SUBCLASS_NAME_lichen_2500m',
       'nwi_WATER_REGIME_NAME_zzz_2500m',
       'nwi_WATER_REGIME_NAME_permanently_flooded_2500m',
       'nwi_SPLIT_CLASS_NAME_emergent_2500m',
       'nwi_WATER_REGIME_SUBGROUP_zzz_2500m',
       'nwi_WATER_REGIME_SUBGROUP_freshwater_tidal_2500m',
       'nwi_CLASS_NAME_rocky_shore_2500m', 'county', 'state'],
      dtype='object', length=486)

In [151]:
df_merged.shape

(14619, 486)

In [152]:
import pickle

# use protocol 3 for backwards compatibility with Python 3.6 on AWS
pickle.dump(df_merged, open("2021.03.19_full_dataset","wb"), protocol=3)
df_merged.to_csv("2021.03.19_full_dataset.csv")

# Read file

In [153]:
df = pd.read_pickle("2021.03.17_full_dataset")

In [154]:
import numpy as np
np.sum(df_merged.dtypes == 'int64') #340
np.sum(df_merged.dtypes == 'object') # 10
np.sum(df_merged.dtypes == 'float64') #107

118

In [155]:
df.loc[:, ["county", "state"]]

          county      state
0         Cayuga     Cayuga
1        Madison    Madison
2        Wyoming    Wyoming
3           Erie       Erie
4        Niagara    Niagara
...          ...        ...
14614  Jefferson  Jefferson
14615     Searcy     Searcy
14616     Rogers     Rogers
14617   Oklahoma   Oklahoma
14618      Kiowa      Kiowa

[14619 rows x 2 columns]

In [156]:
df.head()

,cwa4,cwa8,cwa7,cwa_determination,cwa5,longitude,cwa3,date_issued_or_denied,latitude,Index,...,nwi_SUBCLASS_NAME_non_persistent_2500m,nwi_SPLIT_SUBCLASS_NAME_lichen_2500m,nwi_WATER_REGIME_NAME_zzz_2500m,nwi_WATER_REGIME_NAME_permanently_flooded_2500m,nwi_SPLIT_CLASS_NAME_emergent_2500m,nwi_WATER_REGIME_SUBGROUP_zzz_2500m,nwi_WATER_REGIME_SUBGROUP_freshwater_tidal_2500m,nwi_CLASS_NAME_rocky_shore_2500m,county,state
0,0,0,0,0,0,-76.70773,0,06/19/2020,42.85821,1,...,0,0,0,19,0,0,0,0,Cayuga,Cayuga
1,0,0,0,1,0,-75.85524,1,07/07/2016,43.15230,2,...,0,0,0,17,0,0,0,0,Madison,Madison
2,0,0,0,1,0,-78.04046,0,10/12/2017,42.68911,3,...,0,0,0,8,0,0,0,0,Wyoming,Wyoming
3,0,0,0,1,0,-78.77134,1,06/28/2016,42.97994,4,...,0,0,0,19,0,0,0,0,Erie,Erie
4,0,0,0,1,1,-78.97142,1,03/22/2016,43.21616,5,...,0,0,2,24,0,0,0,0,Niagara,Niagara