In [30]:
import pickle
import pandas as pd

In [31]:
# !ls

In [32]:
# Baseline
df_baseline = pd.read_csv("../../../data/Merge_all_datasets/combined_regular_clean_with_ssurgo_variables.csv")

# NHD
df_nhd_200m = pd.read_pickle("../../../data/Merge_all_datasets/200mX200m_nhd_variables_extracted_stripped")
df_nhd_1000m = pd.read_pickle("../../../data/Merge_all_datasets/1000mX1000m_nhd_variables_extracted_stripped")
df_nhd_2500m = pd.read_pickle("../../../data/Merge_all_datasets/2.5kmX2.5km_nhd_variables_extracted_stripped")

# NHD - nearest waterbodies and flowlines
df_nearest_wotus = pd.read_pickle("../../../data/Merge_all_datasets/nearest_wb_fl_elevation_parts_merged")

# SSURGO
df_ssurgo = pd.read_pickle("../../../data/Merge_all_datasets/2021.03.19_ssurgo_variables_full")

# NWI
df_nwi_200m = pd.read_pickle("../../../data/Merge_all_datasets/nwi_extracted_features_200X200m")
df_nwi_1000m = pd.read_pickle("../../../data/Merge_all_datasets/nwi_extracted_features_1000X1000m")
df_nwi_2500m = pd.read_pickle("../../../data/Merge_all_datasets/nwi_extracted_features_2500X2500m")

# srtm, slope, jrc
df_srtm_200m = pd.read_pickle("../../../data/Merge_all_datasets/df_srtm_slope_variables_200m")
df_srtm_1000m = pd.read_pickle("../../../data/Merge_all_datasets/df_srtm_slope_variables_1000m")
df_srtm_2500m = pd.read_pickle("../../../data/Merge_all_datasets/df_srtm_slope_variables_2500m")

# county
df_county = pd.read_pickle("../../../data/Merge_all_datasets/2021.03.17_us_county_raw")

# HUC
df_huc4 = pd.read_pickle("../../../data/Merge_all_datasets/2021.03.22_huc4")
df_huc6 = pd.read_pickle("../../../data/Merge_all_datasets/2021.03.22_huc6")

In [33]:
# Baseline
full_columns = list(df_baseline.columns)
delete_columns = ['Unnamed: 0', 'Unnamed: 0.1','index','mukey',
       'hydclprs', 'aws025wta', 'drclassdcd',  'project_name', 'rha_determination', 'date_issued_or_denied', 'rha1', 'rha2']

imp_columns = list(set(full_columns) - set(delete_columns))
imp_columns = [col for col in full_columns if (col not in delete_columns)] #list(set(full_columns) - set(delete_columns))
df_baseline = df_baseline[imp_columns]
df_baseline.columns

Index(['jurisdiction_type', 'da_number', 'district', 'longitude', 'latitude',
       'cwa_determination', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6',
       'cwa7', 'cwa8', 'cwa9', 'potential_wetland', 'Index'],
      dtype='object')

In [34]:
df_ssurgo.columns

Index(['Index', 'mukey', 'longitude', 'latitude', 'mustatus', 'slopegradd',
       'slopegradw', 'brockdepmi', 'wtdepannmi', 'wtdepaprju', 'flodfreqdc',
       'flodfreqma', 'pondfreqpr', 'aws025wta', 'aws050wta', 'aws0100wta',
       'aws0150wta', 'drclassdcd', 'drclasswet', 'hydgrpdcd', 'iccdcd',
       'iccdcdpct', 'niccdcd', 'niccdcdpct', 'engdwobdcd', 'engdwbdcd',
       'engdwbll', 'engdwbml', 'engstafdcd', 'engstafll', 'engstafml',
       'engsldcd', 'engsldcp', 'englrsdcd', 'engcmssdcd', 'engcmssmp',
       'urbrecptdc', 'urbrecptwt', 'forpehrtdc', 'hydclprs', 'awmmfpwwta'],
      dtype='object')

In [35]:
# SSURGO
delete_columns = ['mukey', 'latitude', 'longitude', 'mustatus']

full_columns = list(df_ssurgo.columns)
imp_columns = list(set(full_columns) - set(delete_columns))
df_ssurgo = df_ssurgo[imp_columns]
df_ssurgo.columns

Index(['slopegradw', 'drclasswet', 'engstafdcd', 'aws025wta', 'hydgrpdcd',
       'flodfreqdc', 'engstafml', 'englrsdcd', 'niccdcd', 'engdwbdcd',
       'awmmfpwwta', 'iccdcd', 'engdwbll', 'engcmssmp', 'engsldcp',
       'aws0150wta', 'niccdcdpct', 'pondfreqpr', 'slopegradd', 'engdwobdcd',
       'Index', 'urbrecptdc', 'engcmssdcd', 'engsldcd', 'wtdepannmi',
       'engdwbml', 'drclassdcd', 'aws050wta', 'aws0100wta', 'iccdcdpct',
       'forpehrtdc', 'flodfreqma', 'engstafll', 'brockdepmi', 'wtdepaprju',
       'hydclprs', 'urbrecptwt'],
      dtype='object')

In [36]:
# df_nhd_200m.columns

In [37]:
# NHD
full_columns_200m = list(df_nhd_200m.columns)
full_columns_1000m = list(df_nhd_1000m.columns)
full_columns_2500m = list(df_nhd_2500m.columns)
full_columns
delete_columns_200m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb_200m',
       'nhd_vars_fl_200m', 'wb_comid_list_200m', 'wb_ftype_str_list_200m',
       'wb_gnis_id_list_200m', 'wb_area_list_200m', 'fl_comid_list_200m',
       'fl_ftype_str_list_200m', 'fl_gnis_id_list_200m', 'fl_length_list_200m',
                 'wb_comid_str_200m', 'wb_ftype_str_200m', 'wb_gnis_id_str_200m',
                 'fl_comid_str_200m', 'fl_ftype_str_200m',
       'fl_gnis_id_str_200m','fl_ftype_str_vector_200m',
       'wb_ftype_str_vector_200m']

delete_columns_1000m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb_1000m',
       'nhd_vars_fl_1000m', 'wb_comid_list_1000m', 'wb_ftype_str_list_1000m',
       'wb_gnis_id_list_1000m', 'wb_area_list_1000m', 'fl_comid_list_1000m',
       'fl_ftype_str_list_1000m', 'fl_gnis_id_list_1000m', 'fl_length_list_1000m',
                 'wb_comid_str_1000m', 'wb_ftype_str_1000m', 'wb_gnis_id_str_1000m',
                 'fl_comid_str_1000m', 'fl_ftype_str_1000m',
       'fl_gnis_id_str_1000m','fl_ftype_str_vector_1000m',
       'wb_ftype_str_vector_1000m']

delete_columns_2500m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'nhd_vars_wb_2500m',
       'nhd_vars_fl_2500m', 'wb_comid_list_2500m', 'wb_ftype_str_list_2500m',
       'wb_gnis_id_list_2500m', 'wb_area_list_2500m', 'fl_comid_list_2500m',
       'fl_ftype_str_list_2500m', 'fl_gnis_id_list_2500m', 'fl_length_list_2500m',
                 'wb_comid_str_2500m', 'wb_ftype_str_2500m', 'wb_gnis_id_str_2500m',
                 'fl_comid_str_2500m', 'fl_ftype_str_2500m',
       'fl_gnis_id_str_2500m','fl_ftype_str_vector_2500m',
       'wb_ftype_str_vector_2500m']

imp_columns_200m = list(set(full_columns_200m) - set(delete_columns_200m))
imp_columns_1000m = list(set(full_columns_1000m) - set(delete_columns_1000m))
imp_columns_2500m = list(set(full_columns_2500m) - set(delete_columns_2500m))

df_nhd_200m = df_nhd_200m[imp_columns_200m]
df_nhd_1000m = df_nhd_1000m[imp_columns_1000m]
df_nhd_2500m = df_nhd_2500m[imp_columns_2500m]
df_nhd_200m.columns

Index(['fl_totdasqkm_count_200m', 'fl_startflag_count_200m',
       'fl_streamorde_mean_200m', 'fl_intephem_count_200m',
       'fl_ftype_coastline_200m', 'wb_gnis_name_ind_mean_200m',
       'fl_divergence_sum_200m', 'fl_areasqkm_count_200m',
       'fl_flow_type_count_200m', 'wb_ftype_pipeline_200m',
       'wb_gnis_name_ind_count_200m', 'fl_startflag_mean_200m',
       'fl_divergence_count_200m', 'fl_divergence_mean_200m',
       'fl_ftype_pipeline_200m', 'fl_startflag_sum_200m',
       'fl_ftype_artificialpath_200m', 'fl_gnis_name_ind_mean_200m',
       'wb_ftype_streamriver_200m', 'fl_ftype_canalditch_200m',
       'wb_area_mean_200m', 'wb_area_sum_200m', 'wb_gnis_name_ind_sum_200m',
       'Index', 'fl_totdasqkm_mean_200m', 'fl_flow_type_sum_200m',
       'fl_totdasqkm_sum_200m', 'fl_gnis_name_ind_count_200m',
       'wb_ftype_connector_200m', 'fl_length_mean_200m',
       'fl_length_count_200m', 'wb_ftype_canalditch_200m',
       'fl_streamorde_count_200m', 'fl_intephem_mean_200m',
       'fl_ftype_streamriver_200m', 'wb_ftype_artificialpath_200m',
       'fl_flow_type_mean_200m', 'wb_area_count_200m',
       'fl_streamorde_sum_200m', 'fl_areasqkm_sum_200m',
       'fl_areasqkm_mean_200m', 'fl_gnis_name_ind_sum_200m',
       'fl_ftype_connector_200m', 'fl_intephem_sum_200m',
       'wb_ftype_coastline_200m', 'fl_length_sum_200m'],
      dtype='object')

In [38]:
# NHD nearest waterbodies and flowlines

full_columns = list(df_nearest_wotus.columns)
full_columns
delete_columns = ['Unnamed: 0',
 'Unnamed: 0.1',
 'jurisdiction_type',
 'da_number',
 'district',
 'project_name',
 'longitude',
 'latitude',
 'date_issued_or_denied',
 'rha_determination',
 'cwa_determination',
 'rha1',
 'rha2',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'potential_wetland',
 'index',
 'mukey',
 'hydclprs',
 'aws025wta',
 'drclassdcd',
 'nhd_vars_wb_centroid',
 'nhd_vars_fl_centroid',
 'wb_centroid_dist_list',
 'fl_centroid_dist_list',
 'wb_min_index',
 'fl_min_index', 'closest_wb_centroid_coord', 'closest_fl_centroid_coord']
imp_columns = list(set(full_columns) - set(delete_columns))
df_nearest_wotus = df_nearest_wotus[imp_columns]
df_nearest_wotus

,Index,closest_wb_distance_m,closest_fl_elevation,closest_fl_distance_m,closest_fl_area_sqkm,closest_wb_elevation,closest_wb_area_sqkm
0,1,0.19900,114.000000,1.55869,0.1170,434.326797,0.006
1,2,7.21302,112.000000,0.48290,1.4841,112.000000,207.005
2,3,0.82916,413.000000,0.47677,1.1124,413.000000,3.329
3,4,0.78709,188.535948,1.04919,13.9392,187.210526,0.004
4,5,NaN,98.506494,0.84081,0.4644,NaN,NaN
...,...,...,...,...,...,...,...
14614,14615,1.26976,73.600000,1.12851,0.8316,75.573529,0.135
14615,14616,NaN,302.007194,1.04087,5.5170,NaN,NaN
14616,14617,1.36894,179.000000,2.45195,13.1337,174.378571,0.055
14617,14618,NaN,335.000000,0.43727,0.7866,NaN,NaN
14618,14619,1.44951,413.036496,0.35953,3.6135,404.065693,0.014

In [39]:
# NWI
full_columns_200m = list(df_nwi_200m.columns)
full_columns_1000m = list(df_nwi_1000m.columns)
full_columns_2500m = list(df_nwi_2500m.columns)


delete_columns_200m = ['CLASS_NAME_vector_200m',
 'FIRST_MODIFIER_NAME_vector_200m',
 'SPLIT_CLASS_NAME_vector_200m',
 'SPLIT_SUBCLASS_NAME_vector_200m',
 'SUBCLASS_NAME_vector_200m',
 'SUBSYSTEM_NAME_vector_200m',
 'SYSTEM_NAME_vector_200m',
 'Unnamed: 0',
 'Unnamed: 0.1',
 'WATER_REGIME_NAME_vector_200m',
 'WATER_REGIME_SUBGROUP_vector_200m',
 'aws025wta',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'cwa_determination',
 'da_number',
 'date_issued_or_denied',
 'district',
 'drclassdcd',
 'hydclprs',
 'index',
 'jurisdiction_type',
 'latitude',
 'longitude',
 'mukey','nwi_attr_list_200m',
 'nwi_bbox_vars_200m','potential_wetland',
 'project_name',
 'rha1',
 'rha2',
 'rha_determination',
 'wetland_type_vector_200m',
                      'nwi_wetland_list_200m']


delete_columns_1000m = ['CLASS_NAME_vector_1000m',
 'FIRST_MODIFIER_NAME_vector_1000m',
 'SPLIT_CLASS_NAME_vector_1000m',
 'SPLIT_SUBCLASS_NAME_vector_1000m',
 'SUBCLASS_NAME_vector_1000m',
 'SUBSYSTEM_NAME_vector_1000m',
 'SYSTEM_NAME_vector_1000m',
 'Unnamed: 0',
 'Unnamed: 0.1',
 'WATER_REGIME_NAME_vector_1000m',
 'WATER_REGIME_SUBGROUP_vector_1000m',
 'aws025wta',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'cwa_determination',
 'da_number',
 'date_issued_or_denied',
 'district',
 'drclassdcd',
 'hydclprs',
 'index',
 'jurisdiction_type',
 'latitude',
 'longitude',
 'mukey','nwi_attr_list_1000m',
 'nwi_bbox_vars_1000m','potential_wetland',
 'project_name',
 'rha1',
 'rha2',
 'rha_determination',
 'wetland_type_vector_1000m',
                       'nwi_wetland_list_1000m']


delete_columns_2500m = ['CLASS_NAME_vector_2500m',
 'FIRST_MODIFIER_NAME_vector_2500m',
 'SPLIT_CLASS_NAME_vector_2500m',
 'SPLIT_SUBCLASS_NAME_vector_2500m',
 'SUBCLASS_NAME_vector_2500m',
 'SUBSYSTEM_NAME_vector_2500m',
 'SYSTEM_NAME_vector_2500m',
 'Unnamed: 0',
 'Unnamed: 0.1',
 'WATER_REGIME_NAME_vector_2500m',
 'WATER_REGIME_SUBGROUP_vector_2500m',
 'aws025wta',
 'cwa1',
 'cwa2',
 'cwa3',
 'cwa4',
 'cwa5',
 'cwa6',
 'cwa7',
 'cwa8',
 'cwa9',
 'cwa_determination',
 'da_number',
 'date_issued_or_denied',
 'district',
 'drclassdcd',
 'hydclprs',
 'index',
 'jurisdiction_type',
 'latitude',
 'longitude',
 'mukey','nwi_attr_list_2500m',
 'nwi_bbox_vars_2500m','nwi_feature_count_2500m','potential_wetland',
 'project_name',
 'rha1',
 'rha2',
 'rha_determination',
 'wetland_type_vector_2500m',
                       'nwi_wetland_list_2500m']

imp_columns_200m = list(set(full_columns_200m) - set(delete_columns_200m))
imp_columns_1000m = list(set(full_columns_1000m) - set(delete_columns_1000m))
imp_columns_2500m = list(set(full_columns_2500m) - set(delete_columns_2500m))

df_nwi_200m = df_nwi_200m[imp_columns_200m]
df_nwi_1000m = df_nwi_1000m[imp_columns_1000m]
df_nwi_2500m = df_nwi_2500m[imp_columns_2500m]
'nwi_wetland_list_200m' in df_nwi_200m.columns

False

In [40]:
# SRTM, JRC

full_columns_200m = list(df_srtm_200m.columns)
full_columns_1000m = list(df_srtm_1000m.columns)
full_columns_2500m = list(df_srtm_2500m.columns)


delete_columns_200m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'elevation_stats_200m',
       'slope_stats_200m', 'seasonality_stats_200m', 'recurrence_stats_200m',
       'transition_hist', ]

delete_columns_1000m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'elevation_stats_1000m',
       'slope_stats_1000m', 'seasonality_stats_1000m', 'recurrence_stats_1000m',
       'transition_hist', ]



df_srtm_2500m.columns
delete_columns_2500m = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd', 'elevation_stats_2500m',
       'slope_stats_2500m', 'seasonality_stats_2500m',
       'recurrence_stats_2500m', 'transition_hist', ]

imp_columns_200m = list(set(full_columns_200m) - set(delete_columns_200m))
imp_columns_1000m = list(set(full_columns_1000m) - set(delete_columns_1000m))
imp_columns_2500m = list(set(full_columns_2500m) - set(delete_columns_2500m))

df_srtm_200m = df_srtm_200m[imp_columns_200m]
df_srtm_1000m = df_srtm_1000m[imp_columns_1000m]
df_srtm_2500m = df_srtm_2500m[imp_columns_2500m]
df_srtm_200m.columns

Index(['elevation_max_200m', 'transition_1_200m', 'slope_min_200m',
       'elevation_stdev_200m', 'elevation_min_200m', 'transition_6_200m',
       'recurrence_stdev_200m', 'seasonality_mean_200m', 'slope_stdev_200m',
       'recurrence_mean_200m', 'slope_max_200m', 'slope_mean_200m', 'Index',
       'transition_3_200m', 'recurrence_max_200m', 'seasonality_stdev_200m',
       'transition_7_200m', 'seasonality_min_200m', 'transition_4_200m',
       'transition_9_200m', 'transition_5_200m', 'recurrence_min_200m',
       'seasonality_max_200m', 'transition_2_200m', 'elevation_mean_200m',
       'transition_0_200m', 'transition_8_200m'],
      dtype='object')

In [41]:
# County, State

full_columns = list(df_county.columns)

delete_columns = ['Unnamed: 0', 'Unnamed: 0.1', 'jurisdiction_type', 'da_number',
       'district', 'project_name', 'longitude', 'latitude',
       'date_issued_or_denied', 'rha_determination', 'cwa_determination',
       'rha1', 'rha2', 'cwa1', 'cwa2', 'cwa3', 'cwa4', 'cwa5', 'cwa6', 'cwa7',
       'cwa8', 'cwa9', 'potential_wetland', 'index', 'mukey',
       'hydclprs', 'aws025wta', 'drclassdcd',]


imp_columns = list(set(full_columns) - set(delete_columns))

df_county = df_county[imp_columns]
df_county.columns

Index(['county', 'Index', 'state'], dtype='object')

In [42]:
# huc
full_columns = list(df_huc6.columns)
imp_columns = ['Index', 'huc6']
df_huc6 = df_huc6[imp_columns]
df_huc6

       Index    huc6
0          1  041402
1          2  041402
2          3  041300
3          4  041201
4          5  041300
...      ...     ...
14614  14615  111102
14615  14616  110100
14616  14617  110701
14617  14618  110500
14618  14619  111203

[14619 rows x 2 columns]

In [43]:
# huc
full_columns = list(df_huc4.columns)
imp_columns = ['Index', 'huc4']
df_huc4 = df_huc4[imp_columns]
df_huc4

       Index  huc4
0          1  0414
1          2  0414
2          3  0413
3          4  0412
4          5  0413
...      ...   ...
14614  14615  1111
14615  14616  1101
14616  14617  1107
14617  14618  1105
14618  14619  1112

[14619 rows x 2 columns]

In [44]:
# full dataset

df1 = df_baseline

df2 = df_county

df3 = df_huc4
df4 = df_huc6

df5 = df_nearest_wotus

df6 = df_ssurgo

df7 = df_srtm_200m
df8 = df_nhd_200m
df9 = df_nwi_200m

df10 = df_srtm_1000m
df11 = df_nhd_1000m
df12 = df_nwi_1000m

df13 = df_srtm_2500m
df14 = df_nhd_2500m
df15 = df_nwi_2500m



df_merged = pd.merge(df1, df2, on="Index")
df_merged = pd.merge(df_merged, df3, on="Index")
df_merged = pd.merge(df_merged, df4, on="Index")
df_merged = pd.merge(df_merged, df5, on="Index")
df_merged = pd.merge(df_merged, df6, on="Index")
df_merged = pd.merge(df_merged, df7, on="Index")
df_merged = pd.merge(df_merged, df8, on="Index")
df_merged = pd.merge(df_merged, df9, on="Index")
df_merged = pd.merge(df_merged, df10, on="Index")
df_merged = pd.merge(df_merged, df11, on="Index")
df_merged = pd.merge(df_merged, df12, on="Index")
df_merged = pd.merge(df_merged, df13, on="Index")
df_merged = pd.merge(df_merged, df14, on="Index")
df_merged = pd.merge(df_merged, df15, on="Index")
pickle.dump(df_merged, open("../../../data/Merge_all_datasets/2021.04.05_full_dataset","wb"), protocol=3)

In [45]:
# df_merged.columns

In [46]:
# # full dataset

# df1 = df_baseline

# df2 = df_county
# df3 = df_ssurgo

# df4 = df_srtm_200m
# df5 = df_srtm_1000m
# df6 = df_srtm_2500m

# df7 = df_nhd_200m
# df8 = df_nhd_1000m
# df9 = df_nhd_2500m

# df10 = df_nwi_200m
# df11 = df_nwi_1000m
# df12 = df_nwi_2500m

# df13 = df_huc4
# df14 = df_huc6

# df15 = df_nearest_wotus

# df_merged = pd.merge(df1, df2, on="Index")
# df_merged = pd.merge(df_merged, df3, on="Index")
# df_merged = pd.merge(df_merged, df4, on="Index")
# df_merged = pd.merge(df_merged, df5, on="Index")
# df_merged = pd.merge(df_merged, df6, on="Index")
# df_merged = pd.merge(df_merged, df7, on="Index")
# df_merged = pd.merge(df_merged, df8, on="Index")
# df_merged = pd.merge(df_merged, df9, on="Index")
# df_merged = pd.merge(df_merged, df10, on="Index")
# df_merged = pd.merge(df_merged, df11, on="Index")
# df_merged = pd.merge(df_merged, df12, on="Index")
# df_merged = pd.merge(df_merged, df13, on="Index")
# df_merged = pd.merge(df_merged, df14, on="Index")
# df_merged = pd.merge(df_merged, df15, on="Index")
# pickle.dump(df_merged, open("../../../data/Merge_all_datasets/2021.04.05_full_dataset","wb"), protocol=3)

In [47]:
# 200m and 1000m dataset

df1 = df_baseline
df2 = df_ssurgo

df3 = df_srtm_200m
df4 = df_nhd_200m
df5 = df_nwi_200m

# df6 = df_srtm_2500m
# df7 = df_nhd_2500m
# df8 = df_nwi_2500m

df9 = df_county

df10 = df_nearest_wotus

df11 = df_huc4
df12 = df_huc6

df13 = df_srtm_1000m
df14 = df_nhd_1000m
df15 = df_nwi_1000m

df_merged = pd.merge(df1, df2, on="Index")
df_merged = pd.merge(df_merged, df3, on="Index")
df_merged = pd.merge(df_merged, df4, on="Index")
df_merged = pd.merge(df_merged, df5, on="Index")
# df_merged = pd.merge(df_merged, df6, on="Index")
# df_merged = pd.merge(df_merged, df7, on="Index")
# df_merged = pd.merge(df_merged, df8, on="Index")
df_merged = pd.merge(df_merged, df9, on="Index")
df_merged = pd.merge(df_merged, df10, on="Index")
df_merged = pd.merge(df_merged, df11, on="Index")
df_merged = pd.merge(df_merged, df12, on="Index")
df_merged = pd.merge(df_merged, df13, on="Index")
df_merged = pd.merge(df_merged, df14, on="Index")
df_merged = pd.merge(df_merged, df15, on="Index")
pickle.dump(df_merged, open("../../../data/Merge_all_datasets/2021.03.31_200m_1000m","wb"), protocol=3)

In [48]:
# 1000m and 2500m dataset

df1 = df_baseline
df2 = df_ssurgo

# df3 = df_srtm_200m
# df4 = df_nhd_200m
# df5 = df_nwi_200m

df6 = df_srtm_2500m
df7 = df_nhd_2500m
df8 = df_nwi_2500m

df9 = df_county

df10 = df_nearest_wotus

df11 = df_huc4
df12 = df_huc6

df13 = df_srtm_1000m
df14 = df_nhd_1000m
df15 = df_nwi_1000m

df_merged = pd.merge(df1, df2, on="Index")
# df_merged = pd.merge(df_merged, df3, on="Index")
# df_merged = pd.merge(df_merged, df4, on="Index")
# df_merged = pd.merge(df_merged, df5, on="Index")
df_merged = pd.merge(df_merged, df6, on="Index")
df_merged = pd.merge(df_merged, df7, on="Index")
df_merged = pd.merge(df_merged, df8, on="Index")
df_merged = pd.merge(df_merged, df9, on="Index")
df_merged = pd.merge(df_merged, df10, on="Index")
df_merged = pd.merge(df_merged, df11, on="Index")
df_merged = pd.merge(df_merged, df12, on="Index")
df_merged = pd.merge(df_merged, df13, on="Index")
df_merged = pd.merge(df_merged, df14, on="Index")
df_merged = pd.merge(df_merged, df15, on="Index")
pickle.dump(df_merged, open("../../../data/Merge_all_datasets/2021.03.31_1000m_2500m","wb"), protocol=3)

In [49]:
df_merged.shape

(14619, 486)

# Read file

In [50]:
df = pd.read_pickle("../../../data/Merge_all_datasets/2021.04.05_full_dataset")

In [51]:
for col in df.columns:
    print(col)

jurisdiction_type
da_number
district
longitude
latitude
cwa_determination
cwa1
cwa2
cwa3
cwa4
cwa5
cwa6
cwa7
cwa8
cwa9
potential_wetland
Index
county
state
huc4
huc6
closest_wb_distance_m
closest_fl_elevation
closest_fl_distance_m
closest_fl_area_sqkm
closest_wb_elevation
closest_wb_area_sqkm
slopegradw
drclasswet
engstafdcd
aws025wta
hydgrpdcd
flodfreqdc
engstafml
englrsdcd
niccdcd
engdwbdcd
awmmfpwwta
iccdcd
engdwbll
engcmssmp
engsldcp
aws0150wta
niccdcdpct
pondfreqpr
slopegradd
engdwobdcd
urbrecptdc
engcmssdcd
engsldcd
wtdepannmi
engdwbml
drclassdcd
aws050wta
aws0100wta
iccdcdpct
forpehrtdc
flodfreqma
engstafll
brockdepmi
wtdepaprju
hydclprs
urbrecptwt
elevation_max_200m
transition_1_200m
slope_min_200m
elevation_stdev_200m
elevation_min_200m
transition_6_200m
recurrence_stdev_200m
seasonality_mean_200m
slope_stdev_200m
recurrence_mean_200m
slope_max_200m
slope_mean_200m
transition_3_200m
recurrence_max_200m
seasonality_stdev_200m
transition_7_200m
seasonality_min_200m
transition_4_200m
transition_9_200m
transition_5_200m
recurrence_min_200m
seasonality_max_200m
transition_2_200m
elevation_mean_200m
transition_0_200m
transition_8_200m
fl_totdasqkm_count_200m
fl_startflag_count_200m
fl_streamorde_mean_200m
fl_intephem_count_200m
fl_ftype_coastline_200m
wb_gnis_name_ind_mean_200m
fl_divergence_sum_200m
fl_areasqkm_count_200m
fl_flow_type_count_200m
wb_ftype_pipeline_200m
wb_gnis_name_ind_count_200m
fl_startflag_mean_200m
fl_divergence_count_200m
fl_divergence_mean_200m
fl_ftype_pipeline_200m
fl_startflag_sum_200m
fl_ftype_artificialpath_200m
fl_gnis_name_ind_mean_200m
wb_ftype_streamriver_200m
fl_ftype_canalditch_200m
wb_area_mean_200m
wb_area_sum_200m
wb_gnis_name_ind_sum_200m
fl_totdasqkm_mean_200m
fl_flow_type_sum_200m
fl_totdasqkm_sum_200m
fl_gnis_name_ind_count_200m
wb_ftype_connector_200m
fl_length_mean_200m
fl_length_count_200m
wb_ftype_canalditch_200m
fl_streamorde_count_200m
fl_intephem_mean_200m
fl_ftype_streamriver_200m
wb_ftype_artificialpath_200m
fl_flow_type_mean_200m
wb_area_count_200m
fl_streamorde_sum_200m
fl_areasqkm_sum_200m
fl_areasqkm_mean_200m
fl_gnis_name_ind_sum_200m
fl_ftype_connector_200m
fl_intephem_sum_200m
wb_ftype_coastline_200m
fl_length_sum_200m
nwi_shrub_wetland_200m
nwi_SPLIT_CLASS_NAME_aquatic_bed_200m
nwi_SPLIT_SUBCLASS_NAME_mollusk_200m
nwi_WATER_REGIME_NAME_semipermanently_flooded-tidal_200m
nwi_WATER_REGIME_NAME_intermittently_flooded_200m
nwi_CLASS_NAME_zzz_200m
nwi_feature_count_200m
nwi_SUBCLASS_NAME_phragmites_australis_200m
nwi_FIRST_MODIFIER_NAME_managed_200m
nwi_SUBCLASS_NAME_evergreen_200m
nwi_SUBCLASS_NAME_algal_200m
nwi_WATER_REGIME_NAME_seasonally_flooded_200m
nwi_SUBCLASS_NAME_broad-leaved_evergreen_200m
nwi_freshwater_forested_200m
nwi_WATER_REGIME_SUBGROUP_saltwater_tidal_200m
nwi_FIRST_MODIFIER_NAME_euthaline/eusaline_200m
nwi_SPLIT_SUBCLASS_NAME_persistent_200m
nwi_SUBCLASS_NAME_lichen_200m
nwi_FIRST_MODIFIER_NAME_mixohaline/mixosaline_(brackish)_200m
nwi_SPLIT_SUBCLASS_NAME_phragmites_australis_200m
nwi_FIRST_MODIFIER_NAME_partially_drained/ditched_200m
nwi_SPLIT_SUBCLASS_NAME_cobble-gravel_200m
nwi_CLASS_NAME_reef_200m
nwi_SPLIT_CLASS_NAME_reef_200m
nwi_SUBCLASS_NAME_rooted_vascular_200m
nwi_CLASS_NAME_rocky_shore_200m
nwi_WATER_REGIME_SUBGROUP_zzz_200m
nwi_SUBCLASS_NAME_needle-leaved_evergreen_200m
nwi_SUBCLASS_NAME_mollusk_200m
nwi_SPLIT_SUBCLASS_NAME_zzz_200m
nwi_estuarine_and_marine_wetland_200m
nwi_CLASS_NAME_emergent_200m
nwi_CLASS_NAME_unconsolidated_bottom_200m
nwi_WATER_REGIME_NAME_semipermanently_flooded_200m
nwi_WATER_REGIME_NAME_subtidal_200m
nwi_FIRST_MODIFIER_NAME_mineral_200m
nwi_FIRST_MODIFIER_NAME_spoil_200m
nwi_SYSTEM_NAME_estuarine_200m
nwi_FIRST_MODIFIER_NAME_hyperhaline/hypersaline_200m
nwi_SUBCLASS_NAME_moss_200m
nwi_SPLIT_SUBCLASS_NAME_aquatic_moss_200m
nwi_FIRST_MODIFIER_NAME_oligohaline_200m
nwi_SPLIT_SUBCLASS_NAME_organic_200m
nwi_SPLIT_SUBCLASS_NAME_needle-leaved_deciduous_200m
nwi_WATER_REGIME_NAME_permanently_flooded-tidal_200m
nwi_SUBSYSTEM_NAME_limnetic_200m
nwi_SUBSYSTEM_NAME_tidal_200m
nwi_SUBCLASS_NAME_bedrock_200m
nwi_SUBSYSTEM_NAME_intertidal_200m
nwi_WATER_REGIME_NAME_permanently_flooded_200m
nwi_CLASS_NAME_unconsolidated_shore_200m
nwi_SPLIT_SUBCLASS_NAME_non_persistent_200m
nwi_WATER_REGIME_NAME_seasonally_flooded/saturated_200m
nwi_SUBCLASS_NAME_vegetated_200m
nwi_SPLIT_SUBCLASS_NAME_mud_200m
nwi_CLASS_NAME_moss-lichen_200m
nwi_SPLIT_CLASS_NAME_scrub-shrub_200m
nwi_SUBCLASS_NAME_persistent_200m
nwi_WATER_REGIME_NAME_continuously__saturated_200m
nwi_SYSTEM_NAME_lacustrine_200m
nwi_SPLIT_CLASS_NAME_moss-lichen_200m
nwi_SPLIT_SUBCLASS_NAME_evergreen_200m
nwi_SUBCLASS_NAME_cobble-gravel_200m
nwi_SUBCLASS_NAME_needle-leaved_deciduous_200m
nwi_FIRST_MODIFIER_NAME_artificial_substrate_200m
nwi_WATER_REGIME_SUBGROUP_freshwater_tidal_200m
nwi_SPLIT_SUBCLASS_NAME_rooted_vascular_200m
nwi_SUBCLASS_NAME_mud_200m
nwi_SUBCLASS_NAME_aquatic_moss_200m
nwi_WATER_REGIME_NAME_seasonally_flooded-tidal_200m
nwi_freshwater_pond_200m
nwi_SUBSYSTEM_NAME_littoral_200m
nwi_SPLIT_SUBCLASS_NAME_coral_200m
nwi_SUBCLASS_NAME_dead_200m
nwi_WATER_REGIME_NAME_temporary_flooded-tidal_200m
nwi_SPLIT_CLASS_NAME_unconsolidated_bottom_200m
nwi_WATER_REGIME_NAME_irregularly_exposed_200m
nwi_SUBCLASS_NAME_floating_vascular_200m
nwi_WATER_REGIME_SUBGROUP_nontidal_200m
nwi_SUBCLASS_NAME_deciduous_200m
nwi_SUBSYSTEM_NAME_intermittent_200m
nwi_SPLIT_CLASS_NAME_rocky_shore_200m
nwi_FIRST_MODIFIER_NAME_farmed_200m
nwi_CLASS_NAME_streambed_200m
nwi_SUBSYSTEM_NAME_zzz_200m
nwi_SPLIT_SUBCLASS_NAME_broad-leaved_deciduous_200m
nwi_SPLIT_SUBCLASS_NAME_rubble_200m
nwi_SPLIT_SUBCLASS_NAME_vegetated_200m
nwi_SUBCLASS_NAME_zzz_200m
nwi_SYSTEM_NAME_palustrine_200m
nwi_SYSTEM_NAME_marine_200m
nwi_SUBSYSTEM_NAME_unknown_perennial_200m
nwi_FIRST_MODIFIER_NAME_diked/impounded_200m
nwi_SPLIT_CLASS_NAME_emergent_200m
nwi_SPLIT_SUBCLASS_NAME_floating_vascular_200m
nwi_WATER_REGIME_NAME_artificially_flooded_200m
nwi_CLASS_NAME_scrub-shrub_200m
nwi_WATER_REGIME_NAME_temporary_flooded_200m
nwi_SPLIT_CLASS_NAME_unconsolidated_shore_200m
nwi_FIRST_MODIFIER_NAME_polyhaline_200m
nwi_WATER_REGIME_NAME_regularly_flooded_200m
nwi_FIRST_MODIFIER_NAME_zzz_200m
nwi_SPLIT_SUBCLASS_NAME_deciduous_200m
nwi_WATER_REGIME_NAME_seasonally_saturated_200m
nwi_SUBCLASS_NAME_organic_200m
nwi_CLASS_NAME_rock_bottom_200m
nwi_SUBCLASS_NAME_sand_200m
nwi_FIRST_MODIFIER_NAME_acid_200m
nwi_SPLIT_SUBCLASS_NAME_algal_200m
nwi_riverine_200m
nwi_estuarine_and_marine_deepwater_200m
nwi_SUBSYSTEM_NAME_subtidal_200m
nwi_SUBCLASS_NAME_coral_200m
nwi_SUBSYSTEM_NAME_upper_perennial_200m
nwi_CLASS_NAME_forested_200m
nwi_SUBCLASS_NAME_rubble_200m
nwi_SPLIT_CLASS_NAME_forested_200m
nwi_SPLIT_CLASS_NAME_zzz_200m
nwi_FIRST_MODIFIER_NAME_beaver_200m
nwi_SPLIT_SUBCLASS_NAME_bedrock_200m
nwi_WATER_REGIME_NAME_intermittently_exposed_200m
nwi_SPLIT_SUBCLASS_NAME_sand_200m
nwi_SUBCLASS_NAME_non_persistent_200m
nwi_SPLIT_SUBCLASS_NAME_needle-leaved_evergreen_200m
nwi_FIRST_MODIFIER_NAME_alkaline_200m
nwi_freshwater_emergent_wetland_200m
nwi_SPLIT_SUBCLASS_NAME_dead_200m
nwi_lake_200m
nwi_CLASS_NAME_aquatic_bed_200m
nwi_WATER_REGIME_NAME_zzz_200m
nwi_SPLIT_SUBCLASS_NAME_moss_200m
nwi_other_200m
nwi_SPLIT_SUBCLASS_NAME_lichen_200m
nwi_FIRST_MODIFIER_NAME_mesohaline_200m
nwi_FIRST_MODIFIER_NAME_organic_200m
nwi_SUBSYSTEM_NAME_lower_perennial_200m
nwi_SYSTEM_NAME_riverine_200m
nwi_WATER_REGIME_NAME_irregularly_flooded_200m
nwi_SPLIT_SUBCLASS_NAME_broad-leaved_evergreen_200m
nwi_SUBCLASS_NAME_broad-leaved_deciduous_200m
nwi_FIRST_MODIFIER_NAME_excavated_200m
transition_7_1000m
seasonality_mean_1000m
slope_min_1000m
transition_3_1000m
recurrence_min_1000m
seasonality_max_1000m
elevation_max_1000m
elevation_min_1000m
transition_5_1000m
transition_1_1000m
recurrence_stdev_1000m
slope_stdev_1000m
seasonality_stdev_1000m
transition_2_1000m
slope_mean_1000m
slope_max_1000m
transition_9_1000m
transition_8_1000m
elevation_stdev_1000m
recurrence_mean_1000m
seasonality_min_1000m
transition_4_1000m
transition_0_1000m
transition_6_1000m
elevation_mean_1000m
recurrence_max_1000m
fl_gnis_name_ind_sum_1000m
wb_area_sum_1000m
fl_length_sum_1000m
fl_ftype_streamriver_1000m
fl_totdasqkm_sum_1000m
fl_areasqkm_sum_1000m
wb_area_count_1000m
fl_intephem_count_1000m
fl_totdasqkm_mean_1000m
wb_area_mean_1000m
fl_flow_type_sum_1000m
fl_intephem_mean_1000m
wb_ftype_pipeline_1000m
fl_streamorde_sum_1000m
fl_intephem_sum_1000m
fl_length_count_1000m
fl_flow_type_mean_1000m
fl_gnis_name_ind_count_1000m
fl_length_mean_1000m
wb_ftype_streamriver_1000m
fl_divergence_count_1000m
fl_startflag_count_1000m
fl_startflag_mean_1000m
fl_streamorde_mean_1000m
fl_gnis_name_ind_mean_1000m
fl_flow_type_count_1000m
wb_gnis_name_ind_mean_1000m
wb_ftype_artificialpath_1000m
wb_ftype_coastline_1000m
fl_ftype_pipeline_1000m
fl_divergence_sum_1000m
fl_divergence_mean_1000m
fl_areasqkm_count_1000m
wb_gnis_name_ind_count_1000m
wb_ftype_canalditch_1000m
fl_ftype_connector_1000m
fl_totdasqkm_count_1000m
fl_ftype_canalditch_1000m
wb_gnis_name_ind_sum_1000m
fl_startflag_sum_1000m
fl_ftype_artificialpath_1000m
fl_streamorde_count_1000m
fl_ftype_coastline_1000m
wb_ftype_connector_1000m
fl_areasqkm_mean_1000m
nwi_CLASS_NAME_unconsolidated_shore_1000m
nwi_estuarine_and_marine_wetland_1000m
nwi_CLASS_NAME_moss-lichen_1000m
nwi_FIRST_MODIFIER_NAME_acid_1000m
nwi_freshwater_emergent_wetland_1000m
nwi_SUBCLASS_NAME_rubble_1000m
nwi_WATER_REGIME_SUBGROUP_saltwater_tidal_1000m
nwi_SPLIT_SUBCLASS_NAME_rubble_1000m
nwi_WATER_REGIME_NAME_semipermanently_flooded_1000m
nwi_SYSTEM_NAME_marine_1000m
nwi_SPLIT_CLASS_NAME_unconsolidated_shore_1000m
nwi_estuarine_and_marine_deepwater_1000m
nwi_SUBSYSTEM_NAME_intermittent_1000m
nwi_FIRST_MODIFIER_NAME_organic_1000m
nwi_SPLIT_CLASS_NAME_unconsolidated_bottom_1000m
nwi_CLASS_NAME_forested_1000m
nwi_FIRST_MODIFIER_NAME_diked/impounded_1000m
nwi_SUBCLASS_NAME_cobble-gravel_1000m
nwi_feature_count_1000m
nwi_SPLIT_CLASS_NAME_zzz_1000m
nwi_SPLIT_SUBCLASS_NAME_needle-leaved_deciduous_1000m
nwi_WATER_REGIME_NAME_permanently_flooded-tidal_1000m
nwi_FIRST_MODIFIER_NAME_managed_1000m
nwi_other_1000m
nwi_WATER_REGIME_NAME_seasonally_flooded-tidal_1000m
nwi_SUBSYSTEM_NAME_zzz_1000m
nwi_SPLIT_SUBCLASS_NAME_needle-leaved_evergreen_1000m
nwi_FIRST_MODIFIER_NAME_mixohaline/mixosaline_(brackish)_1000m
nwi_lake_1000m
nwi_SUBCLASS_NAME_sand_1000m
nwi_SUBSYSTEM_NAME_littoral_1000m
nwi_SPLIT_CLASS_NAME_rocky_shore_1000m
nwi_FIRST_MODIFIER_NAME_hyperhaline/hypersaline_1000m
nwi_shrub_wetland_1000m
nwi_FIRST_MODIFIER_NAME_zzz_1000m
nwi_CLASS_NAME_aquatic_bed_1000m
nwi_FIRST_MODIFIER_NAME_spoil_1000m
nwi_SUBSYSTEM_NAME_subtidal_1000m
nwi_SPLIT_SUBCLASS_NAME_sand_1000m
nwi_SPLIT_SUBCLASS_NAME_phragmites_australis_1000m
nwi_FIRST_MODIFIER_NAME_polyhaline_1000m
nwi_SUBCLASS_NAME_moss_1000m
nwi_SUBCLASS_NAME_organic_1000m
nwi_SPLIT_SUBCLASS_NAME_algal_1000m
nwi_freshwater_forested_1000m
nwi_SPLIT_SUBCLASS_NAME_dead_1000m
nwi_SUBCLASS_NAME_mud_1000m
nwi_FIRST_MODIFIER_NAME_artificial_substrate_1000m
nwi_SPLIT_CLASS_NAME_reef_1000m
nwi_FIRST_MODIFIER_NAME_oligohaline_1000m
nwi_SPLIT_CLASS_NAME_forested_1000m
nwi_SPLIT_SUBCLASS_NAME_broad-leaved_evergreen_1000m
nwi_WATER_REGIME_NAME_intermittently_flooded_1000m
nwi_WATER_REGIME_NAME_seasonally_flooded/saturated_1000m
nwi_SUBCLASS_NAME_bedrock_1000m
nwi_WATER_REGIME_SUBGROUP_nontidal_1000m
nwi_CLASS_NAME_streambed_1000m
nwi_SPLIT_SUBCLASS_NAME_persistent_1000m
nwi_SUBCLASS_NAME_deciduous_1000m
nwi_CLASS_NAME_reef_1000m
nwi_SPLIT_SUBCLASS_NAME_rooted_vascular_1000m
nwi_WATER_REGIME_NAME_continuously__saturated_1000m
nwi_CLASS_NAME_emergent_1000m
nwi_WATER_REGIME_NAME_seasonally_saturated_1000m
nwi_SUBCLASS_NAME_mollusk_1000m
nwi_FIRST_MODIFIER_NAME_beaver_1000m
nwi_WATER_REGIME_NAME_subtidal_1000m
nwi_SUBCLASS_NAME_needle-leaved_evergreen_1000m
nwi_WATER_REGIME_NAME_zzz_1000m
nwi_riverine_1000m
nwi_SPLIT_SUBCLASS_NAME_bedrock_1000m
nwi_CLASS_NAME_scrub-shrub_1000m
nwi_SPLIT_SUBCLASS_NAME_coral_1000m
nwi_SUBCLASS_NAME_needle-leaved_deciduous_1000m
nwi_FIRST_MODIFIER_NAME_alkaline_1000m
nwi_SUBCLASS_NAME_dead_1000m
nwi_SUBCLASS_NAME_non_persistent_1000m
nwi_SYSTEM_NAME_lacustrine_1000m
nwi_SPLIT_SUBCLASS_NAME_deciduous_1000m
nwi_CLASS_NAME_unconsolidated_bottom_1000m
nwi_SPLIT_SUBCLASS_NAME_mollusk_1000m
nwi_FIRST_MODIFIER_NAME_excavated_1000m
nwi_SPLIT_CLASS_NAME_scrub-shrub_1000m
nwi_SUBCLASS_NAME_coral_1000m
nwi_SUBCLASS_NAME_persistent_1000m
nwi_SPLIT_SUBCLASS_NAME_evergreen_1000m
nwi_SPLIT_SUBCLASS_NAME_broad-leaved_deciduous_1000m
nwi_WATER_REGIME_NAME_seasonally_flooded_1000m
nwi_SUBCLASS_NAME_rooted_vascular_1000m
nwi_SPLIT_SUBCLASS_NAME_floating_vascular_1000m
nwi_SUBSYSTEM_NAME_limnetic_1000m
nwi_SPLIT_SUBCLASS_NAME_lichen_1000m
nwi_SUBCLASS_NAME_floating_vascular_1000m
nwi_SUBSYSTEM_NAME_upper_perennial_1000m
nwi_WATER_REGIME_NAME_temporary_flooded-tidal_1000m
nwi_SPLIT_CLASS_NAME_moss-lichen_1000m
nwi_SUBCLASS_NAME_broad-leaved_evergreen_1000m
nwi_CLASS_NAME_rock_bottom_1000m
nwi_CLASS_NAME_rocky_shore_1000m
nwi_freshwater_pond_1000m
nwi_SPLIT_SUBCLASS_NAME_cobble-gravel_1000m
nwi_SUBCLASS_NAME_lichen_1000m
nwi_SUBCLASS_NAME_algal_1000m
nwi_SUBCLASS_NAME_broad-leaved_deciduous_1000m
nwi_SPLIT_SUBCLASS_NAME_moss_1000m
nwi_FIRST_MODIFIER_NAME_mineral_1000m
nwi_SPLIT_SUBCLASS_NAME_vegetated_1000m
nwi_WATER_REGIME_NAME_temporary_flooded_1000m
nwi_WATER_REGIME_NAME_semipermanently_flooded-tidal_1000m
nwi_SUBSYSTEM_NAME_unknown_perennial_1000m
nwi_SUBCLASS_NAME_evergreen_1000m
nwi_WATER_REGIME_NAME_irregularly_flooded_1000m
nwi_SUBCLASS_NAME_phragmites_australis_1000m
nwi_SUBCLASS_NAME_zzz_1000m
nwi_WATER_REGIME_NAME_irregularly_exposed_1000m
nwi_SPLIT_SUBCLASS_NAME_non_persistent_1000m
nwi_SPLIT_SUBCLASS_NAME_mud_1000m
nwi_SUBCLASS_NAME_vegetated_1000m
nwi_WATER_REGIME_NAME_artificially_flooded_1000m
nwi_SYSTEM_NAME_riverine_1000m
nwi_WATER_REGIME_SUBGROUP_zzz_1000m
nwi_FIRST_MODIFIER_NAME_euthaline/eusaline_1000m
nwi_SPLIT_SUBCLASS_NAME_zzz_1000m
nwi_SUBSYSTEM_NAME_tidal_1000m
nwi_SUBCLASS_NAME_aquatic_moss_1000m
nwi_SYSTEM_NAME_estuarine_1000m
nwi_CLASS_NAME_zzz_1000m
nwi_SPLIT_SUBCLASS_NAME_aquatic_moss_1000m
nwi_SPLIT_SUBCLASS_NAME_organic_1000m
nwi_WATER_REGIME_NAME_regularly_flooded_1000m
nwi_SPLIT_CLASS_NAME_aquatic_bed_1000m
nwi_WATER_REGIME_NAME_intermittently_exposed_1000m
nwi_SUBSYSTEM_NAME_intertidal_1000m
nwi_FIRST_MODIFIER_NAME_farmed_1000m
nwi_FIRST_MODIFIER_NAME_mesohaline_1000m
nwi_SPLIT_CLASS_NAME_emergent_1000m
nwi_SYSTEM_NAME_palustrine_1000m
nwi_WATER_REGIME_NAME_permanently_flooded_1000m
nwi_WATER_REGIME_SUBGROUP_freshwater_tidal_1000m
nwi_FIRST_MODIFIER_NAME_partially_drained/ditched_1000m
nwi_SUBSYSTEM_NAME_lower_perennial_1000m
transition_5_2500m
transition_8_2500m
seasonality_stdev_2500m
slope_max_2500m
recurrence_min_2500m
transition_6_2500m
seasonality_min_2500m
transition_9_2500m
transition_3_2500m
slope_min_2500m
seasonality_mean_2500m
slope_stdev_2500m
recurrence_max_2500m
elevation_min_2500m
transition_1_2500m
seasonality_max_2500m
elevation_stdev_2500m
elevation_max_2500m
slope_mean_2500m
recurrence_stdev_2500m
transition_7_2500m
elevation_mean_2500m
transition_0_2500m
transition_2_2500m
transition_4_2500m
recurrence_mean_2500m
fl_gnis_name_ind_mean_2500m
fl_gnis_name_ind_sum_2500m
fl_length_sum_2500m
fl_divergence_mean_2500m
fl_totdasqkm_sum_2500m
wb_gnis_name_ind_count_2500m
wb_area_sum_2500m
fl_flow_type_count_2500m
fl_intephem_count_2500m
fl_divergence_sum_2500m
fl_ftype_coastline_2500m
wb_ftype_artificialpath_2500m
fl_streamorde_count_2500m
fl_flow_type_sum_2500m
fl_ftype_streamriver_2500m
fl_length_count_2500m
wb_ftype_canalditch_2500m
fl_areasqkm_count_2500m
fl_startflag_mean_2500m
fl_totdasqkm_count_2500m
wb_gnis_name_ind_mean_2500m
fl_startflag_count_2500m
fl_areasqkm_sum_2500m
fl_streamorde_mean_2500m
wb_ftype_coastline_2500m
fl_ftype_connector_2500m
wb_ftype_streamriver_2500m
wb_ftype_pipeline_2500m
fl_ftype_canalditch_2500m
fl_flow_type_mean_2500m
wb_ftype_connector_2500m
fl_streamorde_sum_2500m
fl_areasqkm_mean_2500m
fl_ftype_artificialpath_2500m
wb_gnis_name_ind_sum_2500m
fl_length_mean_2500m
fl_intephem_sum_2500m
wb_area_count_2500m
fl_divergence_count_2500m
wb_area_mean_2500m
fl_startflag_sum_2500m
fl_totdasqkm_mean_2500m
fl_ftype_pipeline_2500m
fl_gnis_name_ind_count_2500m
fl_intephem_mean_2500m
nwi_estuarine_and_marine_deepwater_2500m
nwi_SYSTEM_NAME_palustrine_2500m
nwi_WATER_REGIME_NAME_subtidal_2500m
nwi_WATER_REGIME_NAME_permanently_flooded-tidal_2500m
nwi_SPLIT_SUBCLASS_NAME_evergreen_2500m
nwi_SUBSYSTEM_NAME_subtidal_2500m
nwi_SUBSYSTEM_NAME_intermittent_2500m
nwi_SUBCLASS_NAME_algal_2500m
nwi_CLASS_NAME_rocky_shore_2500m
nwi_WATER_REGIME_NAME_continuously__saturated_2500m
nwi_WATER_REGIME_SUBGROUP_freshwater_tidal_2500m
nwi_WATER_REGIME_NAME_permanently_flooded_2500m
nwi_SUBSYSTEM_NAME_intertidal_2500m
nwi_FIRST_MODIFIER_NAME_mesohaline_2500m
nwi_freshwater_pond_2500m
nwi_WATER_REGIME_NAME_seasonally_saturated_2500m
nwi_SUBCLASS_NAME_persistent_2500m
nwi_SPLIT_SUBCLASS_NAME_broad-leaved_deciduous_2500m
nwi_SYSTEM_NAME_lacustrine_2500m
nwi_CLASS_NAME_moss-lichen_2500m
nwi_SUBSYSTEM_NAME_lower_perennial_2500m
nwi_FIRST_MODIFIER_NAME_acid_2500m
nwi_WATER_REGIME_NAME_irregularly_exposed_2500m
nwi_SPLIT_CLASS_NAME_forested_2500m
nwi_SPLIT_SUBCLASS_NAME_mollusk_2500m
nwi_freshwater_forested_2500m
nwi_SUBCLASS_NAME_phragmites_australis_2500m
nwi_CLASS_NAME_aquatic_bed_2500m
nwi_estuarine_and_marine_wetland_2500m
nwi_WATER_REGIME_SUBGROUP_zzz_2500m
nwi_WATER_REGIME_NAME_seasonally_flooded_2500m
nwi_SUBCLASS_NAME_rooted_vascular_2500m
nwi_FIRST_MODIFIER_NAME_spoil_2500m
nwi_SUBSYSTEM_NAME_unknown_perennial_2500m
nwi_freshwater_emergent_wetland_2500m
nwi_SUBCLASS_NAME_broad-leaved_deciduous_2500m
nwi_FIRST_MODIFIER_NAME_excavated_2500m
nwi_SPLIT_SUBCLASS_NAME_phragmites_australis_2500m
nwi_WATER_REGIME_NAME_artificially_flooded_2500m
nwi_CLASS_NAME_emergent_2500m
nwi_FIRST_MODIFIER_NAME_farmed_2500m
nwi_shrub_wetland_2500m
nwi_SUBCLASS_NAME_deciduous_2500m
nwi_SPLIT_CLASS_NAME_reef_2500m
nwi_WATER_REGIME_NAME_zzz_2500m
nwi_SUBCLASS_NAME_dead_2500m
nwi_SPLIT_SUBCLASS_NAME_rooted_vascular_2500m
nwi_SPLIT_SUBCLASS_NAME_deciduous_2500m
nwi_SYSTEM_NAME_marine_2500m
nwi_CLASS_NAME_reef_2500m
nwi_SPLIT_SUBCLASS_NAME_zzz_2500m
nwi_FIRST_MODIFIER_NAME_partially_drained/ditched_2500m
nwi_FIRST_MODIFIER_NAME_alkaline_2500m
nwi_WATER_REGIME_SUBGROUP_nontidal_2500m
nwi_CLASS_NAME_zzz_2500m
nwi_SPLIT_SUBCLASS_NAME_persistent_2500m
nwi_SUBCLASS_NAME_rubble_2500m
nwi_riverine_2500m
nwi_WATER_REGIME_NAME_regularly_flooded_2500m
nwi_other_2500m
nwi_lake_2500m
nwi_SUBCLASS_NAME_non_persistent_2500m
nwi_CLASS_NAME_streambed_2500m
nwi_SUBSYSTEM_NAME_limnetic_2500m
nwi_WATER_REGIME_NAME_intermittently_flooded_2500m
nwi_SPLIT_SUBCLASS_NAME_algal_2500m
nwi_FIRST_MODIFIER_NAME_artificial_substrate_2500m
nwi_SPLIT_SUBCLASS_NAME_mud_2500m
nwi_SUBCLASS_NAME_aquatic_moss_2500m
nwi_SPLIT_SUBCLASS_NAME_needle-leaved_deciduous_2500m
nwi_SUBSYSTEM_NAME_upper_perennial_2500m
nwi_SPLIT_SUBCLASS_NAME_broad-leaved_evergreen_2500m
nwi_SPLIT_SUBCLASS_NAME_rubble_2500m
nwi_SUBCLASS_NAME_zzz_2500m
nwi_SUBCLASS_NAME_cobble-gravel_2500m
nwi_SPLIT_SUBCLASS_NAME_cobble-gravel_2500m
nwi_SPLIT_CLASS_NAME_zzz_2500m
nwi_SUBCLASS_NAME_needle-leaved_evergreen_2500m
nwi_WATER_REGIME_NAME_intermittently_exposed_2500m
nwi_FIRST_MODIFIER_NAME_hyperhaline/hypersaline_2500m
nwi_WATER_REGIME_NAME_seasonally_flooded/saturated_2500m
nwi_FIRST_MODIFIER_NAME_beaver_2500m
nwi_SPLIT_SUBCLASS_NAME_sand_2500m
nwi_CLASS_NAME_forested_2500m
nwi_SPLIT_SUBCLASS_NAME_vegetated_2500m
nwi_SPLIT_SUBCLASS_NAME_needle-leaved_evergreen_2500m
nwi_SPLIT_CLASS_NAME_unconsolidated_shore_2500m
nwi_SPLIT_SUBCLASS_NAME_lichen_2500m
nwi_SPLIT_CLASS_NAME_emergent_2500m
nwi_SUBCLASS_NAME_sand_2500m
nwi_WATER_REGIME_NAME_temporary_flooded_2500m
nwi_SPLIT_SUBCLASS_NAME_coral_2500m
nwi_SPLIT_SUBCLASS_NAME_bedrock_2500m
nwi_SPLIT_CLASS_NAME_scrub-shrub_2500m

In [52]:
import numpy as np
np.sum(df_merged.dtypes == 'int64') #340
np.sum(df_merged.dtypes == 'object') # 10
np.sum(df_merged.dtypes == 'float64') #107

123

In [53]:
df.niccdcd

0        8.0
1        NaN
2        NaN
3        2.0
4        4.0
        ...
14614    2.0
14615    2.0
14616    7.0
14617    3.0
14618    2.0
Name: niccdcd, Length: 14619, dtype: float64

In [54]:
df.shape

(14619, 698)

In [55]:
df.loc[:, ["county", "state"]]

          county state
0         Cayuga    36
1        Madison    36
2        Wyoming    36
3           Erie    36
4        Niagara    36
...          ...   ...
14614  Jefferson    05
14615     Searcy    05
14616     Rogers    40
14617   Oklahoma    40
14618      Kiowa    40

[14619 rows x 2 columns]

In [56]:
df.head()

,jurisdiction_type,da_number,district,longitude,latitude,cwa_determination,cwa1,cwa2,cwa3,cwa4,...,nwi_SYSTEM_NAME_riverine_2500m,nwi_SPLIT_CLASS_NAME_rocky_shore_2500m,nwi_SYSTEM_NAME_estuarine_2500m,nwi_SPLIT_SUBCLASS_NAME_floating_vascular_2500m,nwi_SPLIT_CLASS_NAME_aquatic_bed_2500m,nwi_FIRST_MODIFIER_NAME_diked/impounded_2500m,nwi_SUBCLASS_NAME_broad-leaved_evergreen_2500m,nwi_SUBSYSTEM_NAME_littoral_2500m,nwi_WATER_REGIME_NAME_temporary_flooded-tidal_2500m,nwi_SPLIT_SUBCLASS_NAME_moss_2500m
0,RAPANOS,LRB-1983-10120,Buffalo,-76.70773,42.85821,0,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
1,RAPANOS,LRB-1985-69031,Buffalo,-75.85524,43.15230,1,0,0,1,0,...,4,0,0,0,0,18,0,0,0,0
2,RAPANOS,LRB-1986-99614,Buffalo,-78.04046,42.68911,1,1,0,0,0,...,9,0,0,0,0,3,0,0,0,0
3,RAPANOS,LRB-1990-97632,Buffalo,-78.77134,42.97994,1,1,0,1,0,...,18,0,0,0,0,0,0,0,0,0
4,RAPANOS,LRB-1991-98611,Buffalo,-78.97142,43.21616,1,0,0,1,0,...,25,0,0,0,0,0,0,0,0,0

In [57]:
# set(df.columns)

In [58]:
df.shape

(14619, 698)